const characters = [
  {
    index: 'baron-zemo',
    name: 'Baron Zemo',
    alias: 'Helmut Zemo',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ['Cabal'],
    attacks: [
      {
        name: 'Sword Strike',
        range: 2,
        damage: 5,
        cost: 0,
        type: 'Physical',
        desc: [
          'After this attack is resolved, this character gains power equal to the damage dealt',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Bleed',
            url: '/api/condition/bleed',
          },
        ],
      },
      {
        name: 'Steel Rush',
        range: 3,
        damage: 6,
        cost: 2,
        type: 'Physical',
        desc: [
          'After this attack is resolved, this character may advance [Medium]',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Bleed',
            text: 'Bleed: After this attack is resolved, the target character gains the Bleed special condition',
          },
        ],
      },
    ],
    superpowers: [
      {
        name: 'Charge',
        type: 'Active',
        cost: 2,
        text: 'Action: This Character immediately makes a move action folled by an attack action. This superpower can be used only once per turn',
      },
      {
        name: 'Counter-Strike',
        type: 'Active',
        cost: 2,
        text: 'After an attack agains this character is resolved, it may use this superpower. If the attacker is withing [range 3], roll four dice. Deal 1 damage to the attacker for each [Crit] and [Wildcard] rolled.',
      },
      {
        name: 'Master Swordsman',
        type: 'Reactive',
        cost: 2,
        text: "When it is the target of a [Physical] attack or targets a character with a [Physical] attack, this character may use this superpower. If the enemy character is within [range 2], this character may reroll any number of it's attack or defence dice.",
      },
      {
        name: 'Strategic Genius',
        type: 'Passive',
        text: 'This character and allied characters with [range 2] may reroll one die in their attack or defence rolls.',
      },
    ],
    baseType: '35mm',
    image: 'images/home/CP01_BaronZemo.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'black-widow',
    name: 'Black Widow',
    alias: 'Natasha Romanova',
    statistics: {
      health: 4,
      speed: 'L',
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 4,
    },

    affiliation: ['A-Force', 'Avengers'],
    attacks: [
      {
        name: 'Strike',
        range: 2,
        damage: 4,
        cost: 0,
        type: 'Energy',
        desc: [
          'After this attack is resolved, this character gains power equal to the damage dealt',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: "Widow's Sting",
            text: 'Bleed: After this attack is resolved, the target character loses 1 [Power]',
          },
        ],
      },
      {
        name: 'Pistol',
        range: 3,
        damage: 4,
        cost: 0,
        type: 'Physical',
      },
      {
        name: 'Mixed Technique',
        range: 2,
        damage: 4,
        cost: 2,
        type: 'Physical',
        desc: [
          'If this attack deals damage, after this attack is resolved, the character gains the Stagger special condition',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Elusive',
            text: 'Elusive: After this attack is resolved, this character may advance [Small]',
          },
        ],
      },
    ],
    superpowers: [
      {
        name: 'Counter-Strike',
        type: 'Active',
        cost: 2,
        text: 'After an attack agains this character is resolved, it may use this superpower. If the attacker is withing [range 3], roll four dice. Deal 1 damage to the attacker for each [Crit] and [Wildcard] rolled.',
      },
      {
        name: 'Martial Artist',
        type: 'Passive',
        text: "When this character is defending against a [Physical] or [Energy] attack targeting it from within [Range 2], this character adds blanks in it's defence roll to it's total successes",
      },
      {
        name: 'Stealth',
        type: 'Passive',
        text: 'Characters must be within [Range 3] of this character to target it with attacks',
      },
    ],
    baseType: '35mm',
    image: 'images/home/CP01_BlackWidow.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'captain-america',
    name: 'Captain America',
    alias: 'Steve Rogers',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [
      {
        name: 'Strike',
        range: 2,
        damage: 5,
        cost: 0,
        type: 'Physical',
        desc: [
          'After this attack is resolved, this character gains power equal to the damage dealt',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Push',
            text: 'Push: If target character is Size 3 or less, before damage is dealt, it may be pushed away from this character [Small]',
          },
        ],
      },
      {
        name: 'Shield Throw',
        range: 4,
        damage: 5,
        cost: 0,
        type: 'Physical',
        desc: [
          'After this attack is resolved, this character gains 1 power.',
          'This attack ignores LOS, and the defending character does not benefit from Cover',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Ricochet',
            text: 'Ricochet: After this attack is resolved, this character may make an additional Shield Throw attack. This attack must target another character within [Range 3] of the original target character and may be any distance from this character. This additional attack does not have the Ricochet special rule',
          },
        ],
      },
      {
        name: 'Shield Slam',
        range: 2,
        damage: 6,
        cost: 2,
        type: 'Physical',
        desc: [
          'If the target character is Size 3 or less, after this attack is resolved, it may be thrown Small.',
        ],
      },
    ],
    superpowers: [
      {
        name: 'A Day Unlike Any Other',
        type: 'Leadership',
        text: 'Each turn you may reduce the power cost of the first superpower used by each allied character by 1, to a minimum of 1.',
      },
      {
        name: 'Bodyguard',
        type: 'Reactive',
        text: 'When another allied character within Rang 2 is targeted by an attack, this character may use this superpower. This character becomes the target of the attack regardless of range or LOS.',
      },
      {
        name: 'Vibranium Shield',
        type: 'Reactive',
        text: "When this character is targeted by a Physical or Energy attack, it may use this superpower. Add two dice to this character's defence roll against that attack.",
      },
    ],
    baseType: '35mm',
    image: 'images/home/CP01_CapAmerica.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP01',
  },

  {
    index: 'captain-marvel-carol-danvers',
    name: 'Captain Marvel',
    alias: 'Carol Danvers',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['Avengers', 'A-Force'],
    attacks: [],
    superpowers: [],
    baseType: '35mm',
    image: 'images/home/CP01_CapMarvel.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'crossbones',
    name: 'Crossbones',
    alias: 'Brock Rumlow',
    statistics: {
      health: 6,
      speed: 'S',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 2,
    },

    affiliation: ['Cabal'],
    attacks: [],
    superpowers: [
      'Strike',
      'Overpower',
      'Haymaker',
      'Inured to Pain',
      'Aggressive',
    ],
    baseType: '35mm',
    image: 'images/home/CP01_Crossbones.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'doctor-octopus',
    name: 'Doctor Octopus',
    alias: 'Otto Octavius',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Spider-Foes'],
    attacks: [],
    superpowers: [
      'Strike',
      'Arm Lasers',
      "Ock's Clutches",
      'Scientific Hubris',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP01_DocOct.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'iron-man',
    name: 'Iron Man',
    alias: 'Tony Stark',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Repulsor Blast',
      'Homing Rockets',
      'Friday AI',
      'Invincible Iron Man',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP01_IronMan.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'red-skull',
    name: 'Red Skull',
    alias: 'Johann Schmidt',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Cabal'],
    attacks: [],
    superpowers: [
      'Strike',
      'Cosmic Blast',
      'Unleashed The Cube',
      'Master of Evil',
      'Cosmic Cube',
      'Master of the Cube',
      'Hail Hydra',
    ],
    baseType: '35mm',
    image: 'images/home/CP01_RedSkull.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'ultron',
    name: 'Ultron',
    alias: 'Ultron',
    statistics: {
      health: 6,
      speed: 'M',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Cabal'],
    attacks: [],
    superpowers: [
      'Strike',
      'Energy Blast',
      'Metallic Fury',
      'Kinetic Field Generator',
      'All Will Be Metal',
      'Analyze and Annihilation',
      'Flight',
      'Immunity [Bleed, Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP01_Ultron.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: 'spiderman',
    name: 'Spider-Man',
    alias: 'Peter Parker',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Web Warriors', 'Defenders'],
    attacks: [],
    superpowers: [
      'Strike',
      'Impact Webbing',
      'Taser Webs',
      'Web Line',
      'Web-A-Pult',
      'Spider-Sense',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP01_Spiderman.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP01',
  },
  {
    index: '1hulk',
    name: 'Hulk',
    alias: 'Bruce Banner',
    statistics: {
      health: 20,
      speed: 'S',
      height: 4,
      points: 6,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Defenders'],
    attacks: [],
    superpowers: [
      'Strike',
      'Thunder Clap',
      'Hulk Smash!',
      'Gamma Leap',
      'Strongest One There Is',
      'Hulk Not Punk Banner',
      'Inner Rage',
      "You Won't Like Me When I Am Angry",
      'Immunity [Poison, Stun]',
    ],
    baseType: '65mm',
    image: 'images/home/CP04_Hulk.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP04',
  },
  {
    index: 'modok',
    name: 'M.O.D.O.K.',
    alias: 'George Charleton',
    statistics: {
      health: 10,
      speed: 'S',
      height: 4,
      points: 5,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Cabal', 'Criminal Syndicate'],
    attacks: [],
    superpowers: [
      'Sword Strike',
      'Steel Rush',
      'Charge',
      'Counter-Strike',
      'Master Swordsman',
      'Strategic Genius',
    ],
    baseType: '65mm',
    image: 'images/home/CP05_Modok.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP05',
  },
  {
    index: '13',
    name: 'Black Panther',
    alias: "T'Challa",
    statistics: {
      health: 6,
      speed: 'L',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Wakanda'],
    attacks: [],
    superpowers: [
      'Strike',
      'Kinetic Burst',
      'King of Wakanda',
      'Mantle of the Black Panther',
      'Pounce',
      'Vibranium Armor',
    ],
    baseType: '35mm',
    image: 'images/home/CP07_BlackPanther.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP07',
  },
  {
    index: 'killmonger',
    name: 'Killmonger',
    alias: "N'Jadaka",
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Cabal', 'Criminal Syndicate', 'Wakanda'],
    attacks: [],
    superpowers: [
      'Vibranium Weapons',
      'Black Ops Strike',
      'Charge',
      'Special Forces',
      'Focused on the Kill',
      'Kill Count',
    ],
    baseType: '35mm',
    image: 'images/home/CP07_Killmonger.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP07',
  },
  {
    index: 'okoye',
    name: 'Okoye',
    alias: 'Okoye',
    statistics: {
      health: 4,
      speed: 'M',
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Wakanda'],
    attacks: [],
    superpowers: [
      'Strike',
      'Vibranium Spear Blast',
      'Bodyguard',
      'General of the Dora Milaje',
      'Martial Artist',
    ],
    baseType: '35mm',
    image: 'images/home/CP08_Okoye.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP08',
  },
  {
    index: 'shuri',
    name: 'Shuri',
    alias: 'Shuri',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Wakanda'],
    attacks: [],
    superpowers: [
      'Panther Gauntlets',
      'Sonic Crush',
      'Super Genius',
      'Upgrades',
      'Head of Wakandan R&D',
    ],
    baseType: '35mm',
    image: 'images/home/CP08_Shuri.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP08',
  },
  {
    index: 'venom',
    name: 'Venom',
    alias: 'Eddie Brock',
    statistics: {
      health: 7,
      speed: 'M',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Spider-Foes', 'Web Warriors'],
    attacks: [],
    superpowers: [
      'Symbiote Tendrils',
      'We Are Venom',
      'Klyntar Rage',
      'So Many Snacks',
      'Symbiote Instincts',
      'Wall Crawler',
    ],
    baseType: '50mm',
    image: 'images/home/CP09_Venom.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP09',
  },
  {
    index: 'spiderman-miles-morales',
    name: 'Spider-Man',
    alias: 'Miles Morales',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Web Warriors'],
    attacks: [],
    superpowers: [
      'Webline Kick',
      'Venom Blast',
      'Great Responsibility',
      'Web Swing',
      'Spider-Sense',
      'Strongest Avenger',
      'Stealth',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP10_Spiderman.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP10',
  },
  {
    index: 'ghost-spider',
    name: 'Ghost-Spider',
    alias: 'Gwen Stacy (Earth-65)',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Web Warriors'],
    attacks: [],
    superpowers: [
      'Spider-Technique',
      'Impact Webbing',
      'Freestyle Beatdown',
      'Web Line',
      'Life Saver',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP10_GhostSpider.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP10',
  },
  {
    index: 'thor',
    name: 'Thor',
    alias: 'Thor Odinson',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['Asgardian', 'Avengers'],
    attacks: [],
    superpowers: [
      'Strike',
      'Hammer Throw',
      'God of Thunder',
      'Prince of Asgard',
      'For Asgard!',
      'Strongest Avenger',
      'Asgardian',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP11_Thor.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP11',
  },
  {
    index: 'valkyrie',
    name: 'Valkyrie',
    alias: 'Brunhilde',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Asgardian'],
    attacks: [],
    superpowers: [
      'Strike',
      'Dragon Fang',
      'Asgardian Might',
      'Charge',
      'Warrior of Legend',
      'Asgardian',
    ],
    baseType: '35mm',
    image: 'images/home/CP11_Valkyrie.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP11',
  },
  {
    index: 'hela-queen-of-hel',
    name: 'Hela, Queen of Hel',
    alias: 'Hela',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 4,
    },

    affiliation: ['Asgardian'],
    attacks: [],
    superpowers: [
      'Hel Forged Blade',
      'Claim Soul',
      'Rain of Hel',
      'Army of Hel',
      'Asgardian',
      'Goddess of Death',
    ],
    baseType: '50mm',
    image: 'images/home/CP12_Hela.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP12',
  },
  {
    index: 'loki-gof-of-mischief',
    name: 'Loki, God of Mischief',
    alias: 'Loki Laufeyson',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Asgardian', 'Cabal'],
    attacks: [],
    superpowers: [
      'Strike',
      'Frost Blast',
      'Illusions',
      'I am a GOD!',
      'Trickster',
      'Asgardian',
      'God of Mischief',
      'Gem Bearer [Mind, Space]',
    ],
    baseType: '35mm',
    image: 'images/home/CP12_Loki.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP12',
  },
  {
    index: 'vision',
    name: 'Vision',
    alias: 'Victor Shade',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 4,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Solar Energy Beam',
      'Synthezoid Avenger',
      'Calculated Trajectory',
      'Synthesis',
      'Rapid Phase',
      'Phasing',
      'Flight',
      'Immunity [Bleed, Poison]',
    ],
    baseType: '35mm',
    image: 'images/home/CP13_Vision.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP13',
  },
  {
    index: 'winter-soldier',
    name: 'Winter Soldier',
    alias: 'James "Bucky" Barnes',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ['Unaffiliated'],
    attacks: [],
    superpowers: [
      'Assault Rifle',
      'Red Fury',
      'Hydra Tactics',
      'Got Your Back',
      'Spetsnaz Training',
    ],
    baseType: '35mm',
    image: 'images/home/CP13_WinterSoldier.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP13',
  },
  {
    index: 'corvus-glaive',
    name: 'Corvus Glaive',
    alias: 'Corvus Glaive',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Black Order'],
    attacks: [],
    superpowers: [
      'Strike',
      'Atom Splitter',
      'Death Blow',
      "Glaive's Edge",
      'Husband of Proxima Midnight',
      'Glaive of Immortality',
      'Gem Bearer [Reality, Time]',
    ],
    baseType: '50mm',
    image: 'images/home/CP15_CorvusGlaive.jpg',
    painted: 'no',
    owned: 'no',
    expansion: 'CP15',
  },
  {
    index: 'proxima-midnight',
    name: 'Proxima Midnight',
    alias: 'Proxima Midnight',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Black Order'],
    attacks: [],
    superpowers: [
      'Strike',
      'Spear Throw',
      'Quantum Starburst',
      'Martial Prowess',
      'Wife of Corvus Glaive',
      'Invulnerability',
    ],
    baseType: '35mm',
    image: 'images/home/CP15_ProximaMidnight.jpg',
    painted: 'no',
    owned: 'no',
    expansion: 'CP15',
  },
  {
    index: 'gamora',
    name: 'Gamora',
    alias: 'Gamora',
    statistics: {
      health: 6,
      speed: 'L',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Guardians of the Galaxy'],
    attacks: [],
    superpowers: [
      'God Slayer',
      'Cosmic Assassin',
      'Assassin Leap',
      'Martial Prowess',
      'Deadliest Woman in the Galaxy',
      'Stealth',
    ],
    baseType: '35mm',
    image: 'images/home/CP16_Gamora.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP16',
  },
  {
    index: 'nebula',
    name: 'Nebula',
    alias: 'Nebula',
    statistics: {
      health: 4,
      speed: 'M',
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ['Guardians of the Galaxy'],
    attacks: [],
    superpowers: [
      'Strike',
      'Blaster Pistol',
      'Show Sword Assault',
      'Assassin',
      'Cybernetic Enhancements',
      'Immunity [Bleed, Poison, Stun]',
    ],
    baseType: '35mm',
    image: 'images/home/CP16_Nebula.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP16',
  },
  {
    index: 'rocket-raccoon',
    name: 'Rocket Raccoon',
    alias: 'Rocket Raccoon',
    statistics: {
      health: 3,
      speed: 'M',
      height: 1,
      points: 2,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Guardians of the Galaxy'],
    attacks: [],
    superpowers: [
      'Plasma Rifle',
      'Hadron Enforcer',
      'Booby Traps',
      'Personal Bodyguards',
      'Nimble',
      'Small Stature',
    ],
    baseType: '35mm',
    image: 'images/home/CP17_Rocket.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP17',
  },
  {
    index: 'groot',
    name: 'Groot',
    alias: 'I Am Groot',
    statistics: {
      health: 7,
      speed: 'S',
      height: 3,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Guardians of the Galaxy'],
    attacks: [],
    superpowers: ['Strike', 'I Am Groot!', 'Living Plant', 'Tangling Vines'],
    baseType: '50mm',
    image: 'images/home/CP17_Groot.jpg',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP17',
  },
  {
    index: 'star-lord',
    name: 'Star-lord',
    alias: 'Peter Quill',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Guardians of the Galaxy'],
    attacks: [],
    superpowers: [
      'Elemental Gun',
      'Full Auto',
      'Winging It',
      'Hit And Run',
      'Plucky Attitude',
      'Flight',
      'Gem Bearer [Power]',
    ],
    baseType: '35mm',
    image: 'images/home/CP18_Starlord.jpg',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP18',
  },
  {
    index: 'black-dwarf',
    name: 'Black Dwarf',
    alias: 'Black Dwarf',
    statistics: {
      health: 6,
      speed: 'S',
      height: 4,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Black Order'],
    attacks: [],
    superpowers: [
      'Axe Strike',
      'Brutal End',
      'Black Fury',
      'Enforced Oblivion',
      'Intimidating Presence',
      'Invulnerable Skin',
    ],
    baseType: '65mm',
    image: 'images/home/CP19_BlackDwarf.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP19',
  },
  {
    index: 'ebony-maw',
    name: 'Ebony Maw',
    alias: 'Ebony Maw',
    statistics: {
      health: 7,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 2,
      energy: 4,
      mystic: 6,
    },

    affiliation: ['Black Order'],
    attacks: [],
    superpowers: [
      'Black Tongue',
      'Herald of Doom',
      'Telekinetic Powerhouse',
      'Telekinetic Deflection',
      'Mind over Matter',
      'Incredible Psychic Potential',
      'Flight',
      'Gem Bearer [Mind, Space]',
    ],
    baseType: '35mm',
    image: 'images/home/CP19_EbonyMaw.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP19',
  },
  {
    index: 'darx-the-destroyer',
    name: 'Drax the Destroyer',
    alias: 'Drax',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ['Guardians of the Galaxy'],
    attacks: [],
    superpowers: [
      'Blades',
      'Headbutt',
      'Titan Killer',
      'The Destroyer',
      'Driven By Vengeance',
      'I Can Take It',
    ],
    baseType: '35mm',
    image: 'images/home/CP20_Drax.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP20',
  },
  {
    index: 'ronan-the-accuser',
    name: 'Ronan the Accuser',
    alias: 'Ronan the Accuser',
    statistics: {
      health: 6,
      speed: 'M',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ['Inhumans', 'Guardians of the Galaxy'],
    attacks: [],
    superpowers: [
      'Strike',
      'Universal Weapon',
      'Kree Justice',
      'Judgment',
      'The Accuser',
      'Gem Bearer [Power]',
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP20_Ronan.png',
    painted: 'nyes',
    owned: 'yes',
    expansion: 'CP20',
  },
  {
    index: 'green-goblin',
    name: 'Green Goblin',
    alias: 'Norman Osborn',
    statistics: {
      health: 7,
      speed: 'M',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Criminal Syndicate', 'Spider-Foes'],
    attacks: [],
    superpowers: [
      'Pumpkin Bombs',
      'Night of the Goblin',
      'Osborn Weaponry',
      'Hit and Run',
      'Trick or Treat',
      'Arch Nemesis (Peter Parker)',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP21_GreenGoblin.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP21',
  },
  {
    index: 'doctor-strange',
    name: 'Doctor Strange',
    alias: 'Stephen Vincent Strange',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ['Convocation', 'Defenders', 'Midnight Sons'],
    attacks: [],
    superpowers: [
      'Bolts of Bedevilment',
      'Crimson Bands of Cyttorak',
      'Mystic Empowerment',
      "Oshtur's Refuge",
      "Hoggoth's Hoary Wisdom",
      'Eye of Agamotto',
      'Shield of the Seraphim',
      'Flight',
      'Gem Bearer [Soul, Time]',
    ],
    baseType: '50mm',
    image: 'images/home/CP23_DoctorStrange.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP23',
  },
  {
    index: 'wong',
    name: 'Wong',
    alias: 'Wong',
    statistics: {
      health: 4,
      speed: 'M',
      height: 2,
      points: 2,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Convocation', 'Defenders', 'Midnight Sons'],
    attacks: [],
    superpowers: [
      'Strike',
      'Faithful Assistant',
      'Meditate',
      "The Vishanti's Blessing",
      'Servant to the Sorcerer Supreme',
    ],
    baseType: '35mm',
    image: 'images/home/CP23_Wong.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP23',
  },
  {
    index: 'black-widow-agent-of-shield',
    name: 'Black Widow, Agent of S.H.I.E.L.D.',
    alias: 'Natasha Romanoff',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Avengers'],
    attacks: [],
    superpowers: [
      'Automatic Pistol',
      'Tear Gas',
      "Widow's Kiss",
      'Interrogate',
      'Parting Shot',
      'Stealth',
    ],
    baseType: '35mm',
    image: 'images/home/CP24_BlackWidow.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP24',
  },
  {
    index: 'hawkeye',
    name: 'Hawkeye',
    alias: 'Clinton Barton',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Defenders'],
    attacks: [],
    superpowers: ['Arrow Shot', 'Hook Arrow', 'Trick Shot', 'Fast Draw'],
    baseType: '35mm',
    image: 'images/home/CP24_Hawkeye.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP24',
  },
  {
    index: 'thanos-the-mad-titan',
    name: 'Thanos, The Mad Titan',
    alias: 'Thanos',
    statistics: {
      health: 8,
      speed: 'M',
      height: 3,
      points: 6,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Black Order'],
    attacks: [],
    superpowers: [
      'Strike',
      'Cosmic Blast',
      "Death's Agenda",
      'Cosmic Portal',
      "Death's Decree",
      'Being of Immeasurable Power',
      'Gem Bearer [Mind, Power, Reality, Soul, Space, Time]',
      'Immunity [Stun]',
    ],
    baseType: '50mm',
    image: 'images/home/CP25_Thanos.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP25',
  },
  {
    index: 'wasp',
    name: 'Wasp (Normal)',
    alias: 'Janet Van Dyne',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Avengers'],
    attacks: [],
    superpowers: [
      'Size-Changing Smack Down',
      'Change Size',
      'Pym Discs',
      'Pym Particle Control',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP26_Wasp.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP26',
  },
  {
    index: 'wasp-tiny',
    name: 'Wasp (Tiny)',
    alias: 'Janet Van Dyne',
    statistics: {
      health: 5,
      speed: 'L',
      height: 1,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Avengers'],
    attacks: [],
    superpowers: [
      'Stinger Blast',
      "Wasp's Fury",
      'Change Size',
      'Tiny Superhero',
      'Stealth',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP26_Wasp.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP26',
  },
  {
    index: 'ant-man',
    name: 'Ant-Man (Normal)',
    alias: 'Scott Lang',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Pym Particle Punch',
      'Bullet Ant Barrage',
      'Change Size',
      'Pym Particle Control',
    ],
    baseType: '35mm',
    image: 'images/home/CP26_AntMan.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP26',
  },
  {
    index: 'ant-man-tiny',
    name: 'Ant-Man (Tiny)',
    alias: 'Scott Lang',
    statistics: {
      health: 5,
      speed: 'S',
      height: 1,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Ant-Sized Uppercut',
      'Change Size',
      'Hitch A Ride',
      'Stealth',
      'Tiny Superhero',
    ],
    baseType: '35mm',
    image: 'images/home/CP26_AntMan.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP26',
  },
  {
    index: 'ghost-rider',
    name: 'Ghost Rider',
    alias: 'Johnathon Blaze',
    statistics: {
      health: 8,
      speed: 'M',
      height: 3,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ['Defenders', 'Midnight Sons'],
    attacks: [],
    superpowers: [
      'Chains of Damnation',
      'Flames of Hell',
      'Penance Stare',
      'Hell on Wheels',
      "Wicked's Judgement",
      'Spirit of Vengeance',
      'Immunity [Bleed, Hex, Incinerate, Poison]',
    ],
    baseType: '65mm',
    image: 'images/home/CP27_GhostRider.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP27',
  },
  {
    index: 'enchantress',
    name: 'Enchantress',
    alias: 'Amora',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 5,
    },

    affiliation: ['Asgard', 'Cabal'],
    attacks: [],
    superpowers: [
      'Spurned Affection',
      'Enthrall',
      "Amora's Kiss",
      'Hel Hath No Fury...',
      "Siren's Call",
      'Asgardian',
      'Enchanting',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP28_Enchantress.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP28',
  },
  {
    index: 'angela',
    name: 'Angela',
    alias: 'Aldrif Odinsdottir',
    statistics: {
      health: 6,
      speed: 'L',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 4,
    },

    affiliation: ['A-Force', 'Asgard', 'Guardians of the Galaxy'],
    attacks: [],
    superpowers: [
      'Xiphos, the Sword of the Stars',
      'Blades of Ichor',
      "Heven's Wrath",
      "Odindottir's Might",
      'Angelic Assassin',
      'Asgardian',
      'Living Ribbons',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP28_Angela.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP28',
  },
  {
    index: 'kingpin',
    name: 'Kingpin',
    alias: 'Wilson Fisk',
    statistics: {
      health: 7,
      speed: 'S',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Cabal', 'Criminal Syndicate', 'Spider-Foes'],
    attacks: [],
    superpowers: [
      'Headbutt',
      'Cane Laser',
      'Hail to the Kin',
      'Illicit Network',
      'Street-Level Negotiations',
      'Intense Physical Conditioning',
      'Solid Frame',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP29_Kingpin.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP29',
  },
  {
    index: 'daredevil',
    name: 'Daredevil',
    alias: 'Matt Murdock',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Defenders', 'Web Warriors'],
    attacks: [],
    superpowers: [
      'Strike',
      'Baton Hook',
      "Devil's Deliverance",
      'Man Without Fear',
      'Radar Sense',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP30_DareDevil.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP30',
  },
  {
    index: 'bullseye',
    name: 'Bullseye',
    alias: 'Benjamin Poindexter',
    statistics: {
      health: 4,
      speed: 'M',
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ['Cabal', 'Crime Syndicate'],
    attacks: [],
    superpowers: [
      'Throwing Knife',
      'Pin Cushion',
      'Hit and Run',
      'I Never Miss',
      'Parting Shot',
    ],
    baseType: '35mm',
    image: 'images/home/CP30_Bullseye.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP30',
  },
  {
    index: 'taskmaster',
    name: 'Taskmaster',
    alias: 'Anthony Masters',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Criminal Syndicate'],
    attacks: [],
    superpowers: [
      'Sword Strike',
      'Shield Throw',
      'Mnemonic Technique',
      'Photographic Reflexes',
      'Intuitive Pattern Recognition',
      'Martial Artist',
      'Rogue Agent',
    ],
    baseType: '35mm',
    image: 'images/home/CP32_Taskmaser.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP32',
  },
  {
    index: 'punisher',
    name: 'Punisher',
    alias: 'Frank Castle',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Unaffiliated'],
    attacks: [],
    superpowers: [
      'Hip Fire',
      'Aimed Shot',
      'No More Second Chances',
      'Spec Ops Training',
      'War Zone',
      'The Fallen',
    ],
    baseType: '35mm',
    image: 'images/home/CP32_Punisher.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP32',
  },
  {
    index: 'dormammu',
    name: 'Dormammu',
    alias: 'Dormammu',
    statistics: {
      health: 10,
      speed: 'M',
      height: 5,
      points: 8,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 5,
    },

    affiliation: ['Dark Dimension'],
    attacks: [],
    superpowers: [
      'Shadow Bolt',
      'Incantation of Obliteration',
      'Flames of the Faltine',
      'Not of this Dimension',
      'Feel the Power of Darkness',
      'Master of the Realm of Darkness',
      'Flight',
      'Immunity [Bleed, Incinerate, Stagger]',
    ],
    baseType: '65mm',
    image: 'images/home/CP33_Dormammu.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP33',
  },
  {
    index: 'black-bolt',
    name: 'Black Bolt',
    alias: 'Blackagar Boltagon',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 2,
    },

    affiliation: ['Inhumans'],
    attacks: [],
    superpowers: [
      'Energy Bolt',
      'Master Punch',
      'King of the Inhumans',
      'Focus Power',
      'Anti-Graviton Field',
      'Inhuman',
      'Flight',
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP34_BlackBolt.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP34',
  },
  {
    index: 'medusa',
    name: 'Medusa',
    alias: 'Medusalith Amazquelin-Boltagon',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Inhumans'],
    attacks: [],
    superpowers: [
      'Braid Bash',
      'Split Ends',
      'Hair Flip',
      'Royal Decree',
      'Inhuman',
      'Living Strands',
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP34_Medusa.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP34',
  },
  {
    index: 'crystal',
    name: 'Crystal',
    alias: 'Crystal Amaquelin',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Inhumans'],
    attacks: [],
    superpowers: [
      'Earth-Shaker',
      'Hurricane Blast',
      'Hydrokinesis',
      'Volcanic Surge',
      'Elemental Onslaught',
      'Elemental Empowerment',
      'Inhuman',
      'Flight',
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP35_Crystal.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP35',
  },
  {
    index: 'lockjaw',
    name: 'Lockjaw',
    alias: 'LockJaw',
    statistics: {
      health: 6,
      speed: 'S',
      height: 3,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Inhumans'],
    attacks: [],
    superpowers: [
      'Bite',
      'DROP IT!',
      'Inter-Dimensional Bloodhound',
      'Teleport',
      'Inhuman',
      "Who's a Good Boy?",
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP35_Lockjaw.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP35',
  },
  {
    index: 'amazing-spider-man',
    name: 'Amazing Spider-Man',
    alias: 'Peter Parker',
    statistics: {
      health: 6,
      speed: 'L',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['Defenders', 'Web Warriors'],
    attacks: [],
    superpowers: [
      'Spider Strike',
      'Whatever a Spider Can',
      'Friendly Neighborhood Spider-Team',
      'Web Swing',
      'Witty Banter',
      'Masterd Spider-Sense',
      'Wall Crawler',
    ],
    baseType: '50mm',
    image: 'images/home/CP37_TheAmazingSpiderman.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP37',
  },
  {
    index: 'black-cat',
    name: 'Black Cat',
    alias: 'Felecia Hardy',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: [
      'A-Force',
      'Criminal Syndicate',
      'Midnight Sons',
      'Web Warriors',
    ],
    attacks: [],
    superpowers: [
      'Cat Claws',
      'Troublemaker',
      'Grappling Hook',
      'Master Cat Burglar',
      'Bad Luck',
      'Stealth',
    ],
    baseType: '50mm',
    image: 'images/home/CP37_BlackCat.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP37',
  },
  {
    index: 'captain-america-sam-wilson',
    name: 'Captain America',
    alias: 'Sam Wilson',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Shield Throw',
      'Redwing Assault',
      'All New, All Different (Affiliation: Avengers)',
      'Charge',
      'Air Lift',
      'Vibranium Shield',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP38_CaptainAmerica.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP38',
  },
  {
    index: 'war-machine',
    name: 'War Machine',
    alias: 'James Rhodes',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Metal Storm',
      'Rocket Pods',
      'Empty the Clip',
      'Titanium Armor Plating',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP38_WarMachine.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP38',
  },
  {
    index: 'she-hulk',
    name: 'She-Hulk',
    alias: 'Jennifer Walters',
    statistics: {
      health: 20,
      speed: 'M',
      height: 3,
      points: 6,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Avengers'],
    attacks: [],
    superpowers: [
      'Sensational Uppercut',
      'The Defense Rests',
      'Defenders of Arcadia (Affiliation: A-Force)',
      'Clear the Court',
      'Superior Weight Training',
      'Legal Defense',
      'Gamma Transfusion',
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP39_SheHulk.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP39',
  },
  {
    index: 'wolverine',
    name: 'Wolverine',
    alias: 'James Logan Howlett',
    statistics: {
      health: 7,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 2,
    },

    affiliation: ['Avengers', 'Defenders', 'Uncanny X-Men', 'X-force'],
    attacks: [],
    superpowers: [
      'Adamantium Slash',
      'Berserker Barrage',
      'The Best At What I Do...',
      'Adamantium Skeleton',
      'Healing Factor [2]',
      'Immunity [Stun]',
    ],
    baseType: '35mm',
    image: 'images/home/CP40_Wolverine.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP40',
  },
  {
    index: 'sabertooth',
    name: 'Sabretooth',
    alias: 'Victor Creed',
    statistics: {
      health: 6,
      speed: 'L',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Brotherhood of Evil Mutants', 'Cabal', 'X-Force'],
    attacks: [],
    superpowers: [
      'Claw Slash',
      'Savage Predator',
      'No Mercy',
      'Untamed Force',
      'Aggressive',
      'Healing Factor [1]',
    ],
    baseType: '35mm',
    image: 'images/home/CP40_Sabretooth.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP40',
  },
  {
    index: 'cyclops',
    name: 'Cyclops',
    alias: 'Scott Summers',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Uncanny X-Men'],
    attacks: [],
    superpowers: [
      'Optic Blast',
      'Optic Devastation',
      'X-Men Blue (Affiliation: Uncanny X-Men)',
      'Field Leader',
      'Hit and Run',
      'Quick Draw',
    ],
    baseType: '35mm',
    image: 'images/home/CP41_Cyclops.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP41',
  },
  {
    index: 'storm',
    name: 'Storm',
    alias: 'Ororo Munroe',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Uncanny X-Men', 'Wakanda'],
    attacks: [],
    superpowers: [
      'Lightning Bolt',
      'Ice Blizzard',
      'Hurricane',
      'X-Men Gold (Affiliation: Uncanny X-Men)',
      'Eye of the Storm',
      'Tempest',
      'Goddess of Storms',
      'Flight',
      'Immunity [Shock]',
    ],
    baseType: '35mm',
    image: 'images/home/CP41_Storm.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP41',
  },
  {
    index: 'magneto',
    name: 'Magneto',
    alias: 'Max Eisenhardt',
    statistics: {
      health: 6,
      speed: 'S',
      height: 2,
      points: 6,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 6,
    },

    affiliation: ['Brotherhood of Mutants', 'Cabal'],
    attacks: [],
    superpowers: [
      'From the Ruins... (Affiliation: Brotherhood of Mutants)',
      'Fatal Attraction',
      'Force Projection',
      'Master of Magnetism',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP42_Magneto.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP42',
  },
  {
    index: 'toad',
    name: 'Toad',
    alias: 'Mortimore Toynbee',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Brotherhood of Mutants'],
    attacks: [],
    superpowers: [
      'Tongue Lash',
      'Spit Acid',
      'Finders Keepers',
      'Hop',
      'Slippery',
      'Prehensile Tongue',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP42_Toad.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP42',
  },
  {
    index: 'beast',
    name: 'Beast',
    alias: 'Hank McCoy',
    statistics: {
      health: 6,
      speed: 'M',
      height: 3,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Inhumans', 'Uncannny X-Men'],
    attacks: [],
    superpowers: [
      'Acrobatic Strike',
      'Animalistic Freestyle',
      'Baser Instincts',
      'Stars and Garters',
      'Disconcerting, Yet Provatative!',
      'Wall Crawler',
    ],
    baseType: '50mm',
    image: 'images/home/CP43_Beast.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP43',
  },
  {
    index: 'mystique',
    name: 'Mystique',
    alias: 'Raven Darkhölme',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Brotherhood of Mutants', 'Cabal'],
    attacks: [],
    superpowers: [
      'Pistol',
      'Espionage',
      'Freedon Force (Affiliation: Brotherhood of Mutants)',
      'Expert Sabotage',
      'Martial Artist',
      'Shapeshifter',
      'Stealth',
    ],
    baseType: '35mm',
    image: 'images/home/CP43_Mystique.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP43',
  },
  {
    index: 'deadpool',
    name: 'Deadpool',
    alias: 'Wade Wilson',
    statistics: {
      health: 4,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Avengers', 'X-Force'],
    attacks: [],
    superpowers: [
      'Stab',
      'Bang',
      'Deodenum Poke',
      'Merc With a Mouth',
      'I Know Karate',
      'Unicorns, Rainbows, and Sugar Plums Dancing Through My Head',
      'Healing Factor [2]',
    ],
    baseType: '35mm',
    image: 'images/home/CP45_Deadpool.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP45',
  },
  {
    index: 'bob-agent-of-hydra',
    name: 'Bob, Agent of Hydra',
    alias: 'Robert Dobalina',
    statistics: {
      health: 3,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 2,
    },

    affiliation: ['Cabal'],
    attacks: [],
    superpowers: [
      'Hydra Pistol',
      'Excessive Violence',
      'Hydra Tactics',
      'Make It Spicy, Bob!',
      'Muy Caliente',
    ],
    baseType: '35mm',
    image: 'images/home/CP45_BobAgentofHydra.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP45',
  },
  {
    index: 'mister-sinister',
    name: 'Mister Sinister',
    alias: 'Nathaniel Essex',
    statistics: {
      health: 6,
      speed: 'M',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Cabal'],
    attacks: [],
    superpowers: [
      'Strike',
      'Genetic Splicing',
      'Recombinant Disintegration',
      'Engeered Perfection',
      'Genetic Negotiation',
      'Such Fun Little Playthings',
      'Molecular Regeneration',
      'DNA Database',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP46_MisterSinister.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP46',
  },
  {
    index: 'cable',
    name: 'Cable',
    alias: 'Nathan Summers',
    statistics: {
      health: 6,
      speed: 'S',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Avengers', 'Uncanny X-Men', 'X-Force'],
    attacks: [],
    superpowers: [
      'Plasma Rifle',
      "Askani'son",
      'Wetworks (Affiliation: X-Force)',
      'Body Slide by One',
      'Omega Level Threat',
      'Telekinetic Shield',
      'Techno-Organic Virus Suppression',
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP47_Cable.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP47',
  },
  {
    index: 'domino',
    name: 'Domino',
    alias: 'Neena Thurman',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['A-Force', 'Uncanny X-Men', 'X-Force'],
    attacks: [],
    superpowers: [
      'Automatic Pistols',
      'Grenade Bounce',
      'Lucky Shot',
      'Probability Manipulation',
      'Things Tend To Go My Way',
    ],
    baseType: '35mm',
    image: 'images/home/CP47_Domino.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP47',
  },
  {
    index: 'blade',
    name: 'Blade',
    alias: 'Eric Brooks',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Avengers', 'Defenders', 'Midnight Sons'],
    attacks: [],
    superpowers: [
      'Katana',
      'Throwing Glaive',
      'Night of the Dhampir',
      'Bump in the Night (Affiliation: Midnight Sons)',
      'Half-Blood Physiology',
      'Supernatural Sense',
      'Vampiric Immortality',
    ],
    baseType: '35mm',
    image: 'images/home/CP48_Blade.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP48',
  },
  {
    index: 'moon-knight',
    name: 'Moon Knight',
    alias: 'Marc Spector',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Defenders', 'Midnight Sons', 'Web Warriors'],
    attacks: [],
    superpowers: [
      'Bo Staff',
      'Throwing Crescents',
      'Avatar of Khonshu',
      'Chosen of Khonshu',
      'Multiple Personalities ',
      'Stealth',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP48_Moonknight.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP48',
  },
  {
    index: 'luke-cage',
    name: 'Luke Cage',
    alias: 'Carl Lucas',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Defenders'],
    attacks: [],
    superpowers: [
      'Power Man Punch',
      'Sweet Christmas',
      'Street Fighter',
      'Too Dangerous to Ignore',
      'Unbreakable Skin',
      'Immunity [Bleed]',
    ],
    baseType: '35mm',
    image: 'images/home/CP49_LukeCage.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP49',
  },
  {
    index: 'iron-fist',
    name: 'Iron Fist',
    alias: 'Danny Rand',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Defenders', 'Midnight Sons'],
    attacks: [],
    superpowers: [
      'Chi Strike',
      'Flying Kick',
      'The Iron Fist',
      'Street Fighter',
      'Immortal Weapon',
      'Master Martial Artist',
    ],
    baseType: '35mm',
    image: 'images/home/CP49_IronFist.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP49',
  },
  {
    index: 'mysterio',
    name: 'Mysterio',
    alias: 'Quentin Beck',
    statistics: {
      health: 6,
      speed: 'S',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 1,
      energy: 1,
      mystic: 5,
    },

    affiliation: ['Cabal', 'Criminal Syndicate', 'Spider-Foes'],
    attacks: [],
    superpowers: [
      'Hypnosis Gas',
      'Curtain Call',
      'Tricks and Traps',
      'Master of Illusions',
      'Smoke and Mirrors',
      'Stealth',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP50_Mysterio.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP50',
  },
  {
    index: 'carnage',
    name: 'Carnage',
    alias: 'Cletus Kasady',
    statistics: {
      health: 7,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 5,
      energy: 1,
      mystic: 1,
    },

    affiliation: ['Spider-Foes'],
    attacks: [],
    superpowers: [
      'Symbiote Tendrils',
      'Maximum Carnage',
      'Sadistic Glee',
      'Paint the Town Red',
      'Arch Nemesis [Eddie Brock]',
      'Symbiotic Serial Killer',
      'Wall Crawler',
    ],
    baseType: '50mm',
    image: 'images/home/CP50_Carnage.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP50',
  },
  {
    index: 'hulkbuster',
    name: 'Hulkbuster',
    alias: 'Tony Stark',
    statistics: {
      health: 13,
      speed: 'M',
      height: 4,
      points: 6,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Heavy Repulsor Blast',
      'Meteor Punch',
      'Hulkbusters (Affiliation: Avengers)',
      'Hit and Run',
      "Now I'm Mad",
      'Built to Take It',
      'Enhanced Support Systems [Iron Man (Hulkbuster)]',
    ],
    baseType: '50mm',
    image: 'images/home/CP52_Hulkbuster.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP52',
  },
  {
    index: 'iron-man-hulkbuster',
    name: 'Iron Man (Hulkbuster)',
    alias: 'Tony Stark',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 6,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Avengers'],
    attacks: [],
    superpowers: [
      'Rapid Repulsor Blast',
      'Hulkbusters (Affiliation: Avengers)',
      'Always Have a Backup',
      'New Plan',
      'Secondary Support Suit',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP52_Hulkbuster.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP52',
  },
  {
    index: 'jean-grey',
    name: 'Jean Grey',
    alias: 'Jean Grey',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 5,
    },

    affiliation: ['Uncanny X-Men'],
    attacks: [],
    superpowers: [
      'Psionic Bolt',
      'Telekinetic Force',
      'Battlefield Manipulation',
      'Matter Transmutaion',
      'Shield Mind',
      'Latent Psychic Potential',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP53_JeanGrey.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP53',
  },
  {
    index: 'cassandra-nova',
    name: 'Cassandra Nova',
    alias: 'Cassandra Nova Xavier',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Cabal'],
    attacks: [],
    superpowers: [
      'Psionic Bolt',
      'Mind Possession',
      'Flesh Manipulation',
      'Biokinesis',
      'Psychic Distraction',
      'Telekinetic Defelction',
      'Telepathic Cloak',
      'Flight',
      'Healing Factor [1]',
    ],
    baseType: '35mm',
    image: 'images/home/CP53_CassandraNova.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP53',
  },
  {
    index: 'omega-red',
    name: 'Omega Red',
    alias: 'Arkady Gregorivich Rossovich',
    statistics: {
      health: 6,
      speed: 'S',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Cabal', 'Criminal Syndicate'],
    attacks: [],
    superpowers: [
      'Carbonadium Coils',
      'Red Terror',
      'Death Factor',
      'Ensnare',
      'Carbonadium Armor',
      'Death Spores',
      'Immunity [Poison]',
    ],
    baseType: '50mm',
    image: 'images/home/CP54_OmegaRed.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP54',
  },

  {
    index: 'nick-fury',
    name: 'Nick Fury',
    alias: 'Nick Fury Jr.',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 2,
    },

    affiliation: [''],
    attacks: [],
    superpowers: [''],
    baseType: '50mm',
    image: 'images/home/CP55_NickFury.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP55',
  },
  {
    index: 'juggernaut',
    name: 'Juggernaut',
    alias: 'Cain Marko',
    statistics: {
      health: 8,
      speed: 'S',
      height: 4,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 5,
    },

    affiliation: ['Brotherhood of Mutants'],
    attacks: [],
    superpowers: [
      'Strike',
      "I'm the Juggernaut",
      'Nothing Stops the Juggernaut!',
      'Nice Punch...',
      'Helmet',
      'Unstoppable Momentum',
      'Immunity [Stun]',
    ],
    baseType: '50mm',
    image: 'images/home/CP56_Juggernaut.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP56',
  },
  {
    index: 'colossus',
    name: 'Colossus',
    alias: 'Piotr Rasputin',
    statistics: {
      health: 6,
      speed: 'S',
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['X-Force'],
    attacks: [],
    superpowers: [
      'Strike',
      'X-Slam',
      'Playing Catch',
      'Big Brother',
      'Bozhe Moi',
      'Organic Steel',
      'Immunity [Bleed]',
    ],
    baseType: 'TBD',
    image: 'images/home/CP57_Colossus.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP57',
  },
  {
    index: 'magik',
    name: 'Magik',
    alias: 'Illyana Rasputin',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Convocation'],
    attacks: [],
    superpowers: [
      'Bolts of Oshtur',
      'Soulsword',
      'Darkchylde',
      'Limbo Step',
      'Sorcerer Supreme of Limbo',
    ],
    baseType: 'TBD',
    image: 'images/home/CP57_Magik.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP57',
  },
  {
    index: 'lizard',
    name: 'Lizard',
    alias: 'Curtis Connor',
    statistics: {
      health: 6,
      speed: 'M',
      height: 3,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Spider-Foes'],
    attacks: [],
    superpowers: [
      'Tail Whip',
      'Cold-Blooded',
      'Biochemical Breakthrough',
      'Thick Hide',
      'Healing Factor [1]',
      'Wall Crawler',
    ],
    baseType: '50mm',
    image: 'images/home/CP58_Lizard.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP58',
  },
  {
    index: 'kraven',
    name: 'Kraven',
    alias: 'Sergei Nikolaevich Kravinoff',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Criminal Syndicate', 'Spider-Foes'],
    attacks: [],
    superpowers: [
      'Kurri Strike',
      'Spear Thrust',
      'Corner the Beast',
      'Expert Tracker',
      'Elixer of Calypso',
    ],
    baseType: '50mm',
    image: 'images/home/CP58_Kraven.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP58',
  },
  {
    index: 'gambit',
    name: 'Gambit',
    alias: 'Remy LeBeau',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['TBD'],
    attacks: [],
    superpowers: [
      'Bo Staff',
      'Kinetic Ace',
      '52 Card Pickup',
      'Accelerate Charge',
      'A Little Something Extra',
      'Enhanced Agility',
    ],
    baseType: 'TBD',
    image: 'images/home/CP60_Gambit.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP60',
  },
  {
    index: 'rogue',
    name: 'Rogue',
    alias: 'Anna Marie LeBeau',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['TBD'],
    attacks: [],
    superpowers: [
      'Absorbing Strike',
      'Southern Hospitality',
      'Charge',
      'Marvelous Strength',
      'Mutant Absorption',
      'Kree-Mutant Physiology',
      'Flight',
      'Immunity [Poison]',
    ],
    baseType: 'TBD',
    image: 'images/home/CP60_Rogue.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP60',
  },
  {
    index: 'sin',
    name: 'Sin',
    alias: 'Sinthea Schmidt',
    statistics: {
      health: 4,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Criminal Syndicate', 'Cabal'],
    attacks: [],
    superpowers: [
      'Automatic Pistol',
      'Make It Personal',
      'Red Mayhem (Affiliation: Cabal)',
      'Hit and Run',
      'Partners in Crime',
      'Heir to the Wicked',
      'Stealth',
    ],
    baseType: '35mm',
    image: 'images/home/CP61_Sin.png',
    painted: 'yes',
    owned: 'yes',
    expansion: 'CP61',
  },
  {
    index: 'viper',
    name: 'Viper',
    alias: 'Ophelia Sarkissian',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Cabal'],
    attacks: [],
    superpowers: [
      'Poisoned Blade',
      "Assassin's Pistol",
      'Viper Strike',
      'Displacement Ring',
      'Coiled Serpent',
      'Stealth',
    ],
    baseType: '35mm',
    image: 'images/home/CP61_Viper.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP61',
  },
  {
    index: 'ms-marvel',
    name: 'Ms. Marvel',
    alias: 'Kamala Khan',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Inhumans'],
    attacks: [],
    superpowers: [
      'Morpho-Punch',
      'Embiggen',
      'Take Out The Trash',
      'Inhuman',
      'Immunity [Poison]',
    ],
    baseType: '35mm',
    image: 'images/home/CP62_MsMarvel.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP62',
  },
  {
    index: 'ms-marvel-embiggen',
    name: 'Ms. Marvel (Embiggened)',
    alias: 'Kamala Khan',
    statistics: {
      health: 5,
      speed: 'M',
      height: 4,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Inhumans'],
    attacks: [],
    superpowers: [
      'High Five',
      'Inhuman',
      'Morphogenetics',
      'Polymorph',
      'Immunity [Poison]',
    ],
    baseType: '65mm',
    image: 'images/home/CP62_MsMarvel-embiggen.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP62',
  },
  {
    index: 'scarlet-witch',
    name: 'Scarlet Witch',
    alias: 'Wanda Maximoff',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ['A-Force', 'Avengers', 'Defenders', 'Brotherhood of Mutants'],
    attacks: [],
    superpowers: [
      'Hex Bolt',
      'Cruel Twist',
      'Telekinesis',
      'Curse',
      'Chosen of Chthon',
      'Hex Field',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP63_ScarletWitch.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP63',
  },
  {
    index: 'quicksilver',
    name: 'Quicksilver',
    alias: 'Pietro Maximoff',
    statistics: {
      health: 5,
      speed: 'L',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ['Avengers', 'Brotherhood of Mutants', 'Inhumans'],
    attacks: [],
    superpowers: [
      'Supersonic Strike',
      'Cyclonic Vortex',
      '"speed"ster',
      "Can't Catch Me",
      'Supersonic Reflexes',
      'Wall Crawler',
    ],
    baseType: '35mm',
    image: 'images/home/CP63_Quicksilver.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP63',
  },
  {
    index: 'ancient-one',
    name: 'Ancient One',
    alias: 'Ancient One',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 5,
    },

    affiliation: ['Convocation', 'Defenders'],
    attacks: [],
    superpowers: [
      'Shards of Seraphim',
      'Fangs of Farallah',
      'Astral Strike',
      'Mists of Hoggoth',
      'Winds of Watoomb',
      'Keeper of the Eye of Agamotto',
      'Martial Artist',
    ],
    baseType: '35mm',
    image: 'images/home/CP64_AncientOne.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP64',
  },
  {
    index: 'baron-mordo',
    name: 'Baron Mordo',
    alias: 'Karl Amadeus Mordo',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 4,
      mystic: 4,
    },

    affiliation: ['Cabal', 'Convocation'],
    attacks: [],
    superpowers: [
      'Staf of the Living Tribunal',
      'Bolts of Bishru',
      'Rains fo Raggadorr',
      'Master of the Occult',
      'Soul Barb',
      'Ferocity of Cyttorak',
      'Vaulting Boots of Valtor',
      'Flight',
    ],
    baseType: '35mm',
    image: 'images/home/CP64_Mordo.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP64',
  },
  {
    index: 'doctor-voodoo',
    name: 'Doctor Voodoo',
    alias: 'Jericho Drumm',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 4,
    },

    affiliation: ['Avengers', 'Convocation', 'Midnight Sons'],
    attacks: [],
    superpowers: [
      'Sprit Venom',
      'Staff of Legba',
      'Possession',
      'Spiritual Strength',
      'Recall Spirit',
      'Spirit of Brother Daniel',
      'Flight',
      'Immunity [Hex, Incinerate]',
    ],
    baseType: '50mm',
    image: 'images/home/CP65_DoctorVoodoo.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP65',
  },
  {
    index: 'hood',
    name: 'Hood (Normal)',
    alias: 'Parker Robbins',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Cabal', 'Crime Syndicate'],
    attacks: [],
    superpowers: [
      'Hex Shot',
      'Dark Lightning',
      'Black Arts',
      'Invisibility Cloak',
      'Possessed by Nasanti',
    ],
    baseType: '35mm',
    image: 'images/home/CP65_Hood.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP65',
  },
  {
    index: 'hood-possessed',
    name: 'Hood (Possessed)',
    alias: 'Parker Robbins',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ['Cabal', 'Crime Syndicate'],
    attacks: [],
    superpowers: [
      'Razor Talons',
      'Empowered Dark Lightning',
      'Charge',
      'Demonic Resilience',
      'Mystic Vulnerability',
    ],
    baseType: '35mm',
    image: 'images/home/CP65_HoodPossessed.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP65',
  },
  {
    index: 'doctor-strange-sorcerer-supreme',
    name: 'Doctor Strange, Sorcerer Supreme',
    alias: 'Stephen Vincent Strange',
    statistics: {
      health: 6,
      speed: 'M',
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 5,
    },

    affiliation: ['Convocation', 'Defenders', 'Midnight Sons'],
    attacks: [],
    superpowers: [
      'Baleful Bolts of Balthakk',
      'Deadly Daggers of Daveroth',
      'Shining Circle of the Serphim',
      'Scalpel of St"range"',
      'Chosen of the Vishanti',
      'Eye of Agamotto',
      'Mystic Armor of St"range"',
      'Flight',
    ],
    baseType: '50mm',
    image: 'images/home/CP67_DoctorStrange.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP67',
  },
  {
    index: 'clea',
    name: 'Clea',
    alias: 'Clea',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 4,
    },

    affiliation: ['Convocation', 'Defenders'],
    attacks: [],
    superpowers: [
      'Demon Claws of Denak',
      'Icy Tendrils of Ikthalon',
      'Descendant of the Faultine',
      "Oshtur's Mighty Hand",
      'Vapors of Dormammu',
      'Immunity [Incinerate]',
    ],
    baseType: '50mm',
    image: 'images/home/CP67_Clea.png',
    painted: 'no',
    owned: 'no',
    expansion: 'CP67',
  },
  //CP68 Sanctum Sanctorum
  //CP69 ?/?
  //CP70 ?/?
  {
    index: 'honesy-badger',
    name: 'Honey Badger',
    alias: 'Gabrielle Kinney',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 2,
    },

    affiliation: [''],
    attacks: [
      {
        name: 'Claw Slash',
        range: 2,
        damage: 5,
        cost: 0,
        type: 'Physical',
        desc: [
          'After this attack is resolved, this character gains power equal to the damage dealt',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Bleed',
            text: 'Bleed: After this attack is resolved, the target character gains the Bleed special condition',
          },
        ],
      },
    ],
    superpowers: [
      'Too Dangerous to Ignore',
      'Anklebiter',
      "Lil' Sis",
      'Healing Factor [1]',
    ],
    baseType: '50mm',
    image: 'images/home/CP71_Honeybadger.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP71',
  },
  {
    index: 'x-23',
    name: 'X-23',
    alias: 'Laura Kinney',
    statistics: {
      health: 5,
      speed: 'M',
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: [''],
    attacks: [
      {
        name: 'Adamantium Slash',
        range: 2,
        damage: 5,
        cost: 0,
        type: 'Physical',
        desc: [
          'After this attack is resolved, this character gains power equal to the damage dealt',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Bleed',
            text: 'Bleed: After this attack is resolved, the target character gains the Bleed special condition',
          },
        ],
      },
      {
        name: 'Adamantium Slash',
        range: 2,
        damage: 5,
        cost: 0,
        type: 'Physical',
        desc: [
          'After this attack is resolved, this character gains power equal to the damage dealt',
        ],
        special: [
          {
            wildcardcost: '1',
            skullcost: '',
            critcost: '',
            keyword: 'Bleed',
            text: 'Bleed: After this attack is resolved, the target character gains the Bleed special condition',
          },
        ],
      },
    ],
    superpowers: [
      'Too Dangerous to Ignore',
      'Anklebiter',
      "Lil' Sis",
      'Healing Factor [1]',
    ],
    baseType: '50mm',
    image: 'images/home/CP71_Honeybadger.png',
    painted: 'no',
    owned: 'yes',
    expansion: 'CP71',
  },
]

module.exports = characters
