const characters = [
  {
    _id: "1",
    name: "Baron Zemo",
    alias: "Helmut Zemo",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ["Cabal"],
    attacks: {
      attack1: {
        name: "Sword Strike",
        range: 2,
        damage: 5,
        cost: 0,
        type: "Physical",
        attackDesc: [
          [
            "After this attack is resolved, this character gains power equal to the damage dealt",
          ],
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Bleed",
            url: "/api/condition/bleed",
          },
        ],
      },
      attack2: {
        name: "Steel Rush",
        range: 3,
        damage: 6,
        cost: 2,
        type: "Physical",
        attackDesc: [
          "After this attack is resolved, this character may advance [Medium]",
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Bleed",
            text: "Bleed: After this attack is resolved, the target character gains the Bleed special condition",
          },
        ],
      },
    },
    superpowers: {
      superpower1: {
        name: "Charge",
        type: "Active",
        cost: 2,
        text: "Action: This Character immediately makes a move action folled by an attack action. This superpower can be used only once per turn",
      },
      superpower2: {
        name: "Counter-Strike",
        type: "Active",
        cost: 2,
        text: "After an attack agains this character is resolved, it may use this superpower. If the attacker is withing [range 3], roll four dice. Deal 1 damage to the attacker for each [Crit] and [Wildcard] rolled.",
      },
      superpower3: {
        name: "Master Swordsman",
        type: "Reactive",
        cost: 2,
        text: "When it is the target of a [Physical] attack or trgets a character with a [Physical] attack, this character may use this superpower. If the enemy character is within [range 2], this character may reroll any number of it's attack or defence dice.",
      },
      superpower4: {
        name: "Strategic Genius",
        type: "Passive",
        text: "This character and allied characters with [range 2] may reroll one die in their attack or defence rolls.",
      },
    },
    baseType: "35mm",
    image: "images/home/CP01_BaronZemo.jpg",
    expansion: "CP01",
  },
  {
    _id: "2",
    name: "Black Widow",
    alias: "Natasha Romanova",
    statistics: {
      health: 4,
      speed: "L",
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 4,
    },

    affiliation: ["A-Force", "Avengers"],
    attacks: {
      attack1: {
        name: "Strike",
        range: 2,
        damage: 4,
        cost: 0,
        type: "Energy",
        attackDesc: [
          "After this attack is resolved, this character gains power equal to the damage dealt",
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Widow's Sting",
            text: "Bleed: After this attack is resolved, the target character loses 1 [Power]",
          },
        ],
      },
      attack2: {
        name: "Pistol",
        range: 3,
        damage: 4,
        cost: 0,
        type: "Physical",
      },
      attack3: {
        name: "Mixed Technique",
        range: 2,
        damage: 4,
        cost: 2,
        type: "Physical",
        attackDesc: [
          "If this attack deals damage, after this attack is resolved, the character gains the Stagger special condition",
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Elusive",
            text: "Elusive: After this attack is resolved, this character may advance [Small]",
          },
        ],
      },
    },
    superpowers: {
      superpower1: {
        name: "Counter-Strike",
        type: "Active",
        cost: 2,
        text: "After an attack agains this character is resolved, it may use this superpower. If the attacker is withing [range 3], roll four dice. Deal 1 damage to the attacker for each [Crit] and [Wildcard] rolled.",
      },
      superpower2: {
        name: "Martial Artist",
        type: "Passive",
        text: "When this character is defending against a [Physical] or [Energy] attack targeting it from within [Range 2], this character adds blanks in it's defence roll to it's total successes",
      },
      superpower3: {
        name: "Stealth",
        type: "Passive",
        text: "Characters must be within [Range 3] of this character to target it with attacks",
      },
    },
    baseType: "35mm",
    image: "images/home/CP01_BlackWidow.jpg",
    expansion: "CP01",
  },
  {
    _id: "3",
    name: "Captain America",
    alias: "Steve Rogers",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {
      attack1: {
        name: "Strike",
        range: 2,
        damage: 5,
        cost: 0,
        type: "Physical",
        attackDesc: [
          "After this attack is resolved, this character gains power equal to the damage dealt",
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Push",
            text: "Push: If target character is Size 3 or less, before damage is dealt, it may be pushed away from this character [Small]",
          },
        ],
      },
      attack2: {
        name: "Shield Throw",
        range: 4,
        damage: 5,
        cost: 0,
        type: "Physical",
        attackDesc: [
          "After this attack is resolved, this character gains 1 power. This attack ignores LOS, and the defending character does not benefit from Cover.",
          "This attack ignores LOS, and the defending character does not benefit from Cover",
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Ricochet",
            text: "Ricochet: After this attack is resolved, this character may make an additional Shield Throw attack. This attack must target another character within [Range 3] of the original target character and may be any distance from this character. This additional attack does not have the Ricochet special rule",
          },
        ],
      },
      attack3: {
        name: "Shield Slam",
        range: 2,
        damage: 6,
        cost: 2,
        type: "Physical",
        attackDesc: [
          "If the target character is Size 3 or less, after this attack is resolved, it may be thrown Small.",
        ],
      },
      superpowers: {
        superpower1: {
          name: "A Day Unlike Any Other",
          type: "Leadership",
          text: "Each turn you may reduce the power cost of the first superpower used by each allied character by 1, to a minimum of 1.",
        },
        superpower2: {
          name: "Bodyguard",
          type: "Reactive",
          text: "When another allied character within Rang 2 is targeted by an attack, this character may use this superpower. This character becomes the target of the attack regardless of range or LOS.",
        },
        superpower3: {
          name: "Vibranium Shield",
          type: "Reactive",
          text: "When this character is targeted by a Physical or Energy attack, it may use this superpower. Add two dice to this character's defence roll against that attack.",
        },
      },
    },
    baseType: "35mm",
    image: "images/home/CP01_CapAmerica.jpg",
    expansion: "CP01",
  },

  {
    _id: "4",
    name: "Captain Marvel",
    alias: "Carol Danvers",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["Avengers", "A-Force"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "energy Blast",
      power3: "Rocket Punch",
      power4: "Binary Form",
      power5: "Danvers' Special",
      power6: "Energy Absorption",
      power7: "Flight",
      power8: "Immunity [Incinerate, Poison]",
    },
    baseType: "35mm",
    image: "images/home/CP01_CapMarvel.jpg",
    expansion: "CP01",
  },
  {
    _id: "5",
    name: "Crossbones",
    alias: "Brock Rumlow",
    statistics: {
      health: 6,
      speed: "S",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 2,
    },

    affiliation: ["Cabal"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Overpower",
      power3: "Haymaker",
      power4: "Inured to Pain",
      power5: "Aggressive",
    },
    baseType: "35mm",
    image: "images/home/CP01_Crossbones.jpg",
    expansion: "CP01",
  },
  {
    _id: "6",
    name: "Doctor Octopus",
    alias: "Otto Octavius",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Spider-Foes"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Arm Lasers",
      power3: "Ock's Clutches",
      power4: "Scientific Hubris",
      power5: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP01_DocOct.jpg",
    expansion: "CP01",
  },
  {
    _id: "7",
    name: "Iron Man",
    alias: "Tony Stark",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Repulsor Blast",
      power2: "Homing Rockets",
      power3: "Friday AI",
      power4: "Invincible Iron Man",
      power5: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP01_IronMan.jpg",
    expansion: "CP01",
  },
  {
    _id: "8",
    name: "Red Skull",
    alias: "Johann Schmidt",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Cabal"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Cosmic Blast",
      power3: "Unleashed The Cube",
      power4: "Master of Evil",
      power5: "Cosmic Cube",
      power6: "Master of the Cube",
      power7: "Hail Hydra",
    },
    baseType: "35mm",
    image: "images/home/CP01_RedSkull.jpg",
    expansion: "CP01",
  },
  {
    _id: "9",
    name: "Ultron",
    alias: "Ultron",
    statistics: {
      health: 6,
      speed: "M",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Cabal"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Energy Blast",
      power3: "Metallic Fury",
      power4: "Kinetic Field Generator",
      power5: "All Will Be Metal",
      power6: "Analyze and Annihilation",
      power7: "Flight",
      power8: "Immunity [Bleed, Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP01_Ultron.jpg",
    expansion: "CP01",
  },
  {
    _id: "10",
    name: "Spider-Man",
    alias: "Peter Parker",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Web Warriors", "Defenders"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Impact Webbing",
      power3: "Taser Webs",
      power4: "Web Line",
      power5: "Web-A-Pult",
      power6: "Spider-Sense",
      power7: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP01_Spiderman.jpg",
    expansion: "CP01",
  },
  {
    _id: "11",
    name: "Hulk",
    alias: "Bruce Banner",
    statistics: {
      health: 20,
      speed: "S",
      height: 4,
      points: 6,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers", "Defenders"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Thunder Clap",
      power3: "Hulk Smash!",
      power4: "Gamma Leap",
      power5: "Strongest One There Is",
      power6: "Hulk Not Punk Banner",
      power7: "Inner Rage",
      power8: "You Won't Like Me When I Am Angry",
      power9: "Immunity [Poison, Stun]",
    },
    baseType: "65mm",
    image: "images/home/CP04_Hulk.jpg",
    expansion: "CP04",
  },
  {
    _id: "12",
    name: "M.O.D.O.K.",
    alias: "George Charleton",
    statistics: {
      health: 10,
      speed: "S",
      height: 4,
      points: 5,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Cabal", "Criminal Syndicate"],
    attacks: {},
    superpowers: {
      power1: "Sword Strike",
      power2: "Steel Rush",
      power3: "Charge",
      power4: "Counter-Strike",
      power5: "Master Swordsman",
      power6: "Strategic Genius",
    },
    baseType: "65mm",
    image: "images/home/CP05_Modok.jpg",
    expansion: "CP05",
  },
  {
    _id: "13",
    name: "Black Panther",
    alias: "T'Challa",
    statistics: {
      health: 6,
      speed: "L",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers", "Wakanda"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Kinetic Burst",
      power3: "King of Wakanda",
      power4: "Mantle of the Black Panther",
      power5: "Pounce",
      power6: "Vibranium Armor",
    },
    baseType: "35mm",
    image: "images/home/CP07_BlackPanther.jpg",
    expansion: "CP07",
  },
  {
    _id: "14",
    name: "Killmonger",
    alias: "N'Jadaka",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Cabal", "Criminal Syndicate", "Wakanda"],
    attacks: {},
    superpowers: {
      power1: "Vibranium Weapons",
      power2: "Black Ops Strike",
      power3: "Charge",
      power4: "Special Forces",
      power5: "Focused on the Kill",
      power6: "Kill Count",
    },
    baseType: "35mm",
    image: "images/home/CP07_Killmonger.jpg",
    expansion: "CP07",
  },
  {
    _id: "15",
    name: "Okoye",
    alias: "Okoye",
    statistics: {
      health: 4,
      speed: "M",
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["A-Force", "Wakanda"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Vibranium Spear Blast",
      power3: "Bodyguard",
      power4: "General of the Dora Milaje",
      power5: "Martial Artist",
    },
    baseType: "35mm",
    image: "images/home/CP08_Okoye.jpg",
    expansion: "CP08",
  },
  {
    _id: "16",
    name: "Shuri",
    alias: "Shuri",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["A-Force", "Wakanda"],
    attacks: {},
    superpowers: {
      power1: "Panther Gauntlets",
      power2: "Sonic Crush",
      power3: "Super Genius",
      power4: "Upgrades",
      power5: "Head of Wakandan R&D",
    },
    baseType: "35mm",
    image: "images/home/CP08_Shuri.jpg",
    expansion: "CP08",
  },
  {
    _id: "17",
    name: "Venom",
    alias: "Eddie Brock",
    statistics: {
      health: 7,
      speed: "M",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Spider-Foes", "Web Warriors"],
    attacks: {},
    superpowers: {
      power1: "Symbiote Tendrils",
      power2: "We Are Venom",
      power3: "Klyntar Rage",
      power4: "So Many Snacks",
      power5: "Symbiote Instincts",
      power6: "Wall Crawler",
    },
    baseType: "50mm",
    image: "images/home/CP09_Venom.jpg",
    expansion: "CP09",
  },
  {
    _id: "18",
    name: "Spider-Man",
    alias: "Miles Morales",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Web Warriors"],
    attacks: {},
    superpowers: {
      power1: "Webline Kick",
      power2: "Venom Blast",
      power3: "Great Responsibility",
      power4: "Web Swing",
      power5: "Spider-Sense",
      power6: "Strongest Avenger",
      power7: "Stealth",
      power8: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP10_Spiderman.jpg",
    expansion: "CP10",
  },
  {
    _id: "19",
    name: "Ghost-Spider",
    alias: "Gwen Stacy (Earth-65)",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Web Warriors"],
    attacks: {},
    superpowers: {
      power1: "Spider-Technique",
      power2: "Impact Webbing",
      power3: "Freestyle Beatdown",
      power4: "Web Line",
      power5: "Life Saver",
      power6: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP10_GhostSpider.jpg",
    expansion: "CP10",
  },
  {
    _id: "20",
    name: "Thor",
    alias: "Thor Odinson",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["Asgardian", "Avengers"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Hammer Throw",
      power3: "God of Thunder",
      power4: "Prince of Asgard",
      power5: "For Asgard!",
      power6: "Strongest Avenger",
      power7: "Asgardian",
      power8: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP11_Thor.jpg",
    expansion: "CP11",
  },
  {
    _id: "21",
    name: "Valkyrie",
    alias: "Brunhilde",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Asgardian"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Dragon Fang",
      power3: "Asgardian Might",
      power4: "Charge",
      power5: "Warrior of Legend",
      power6: "Asgardian",
    },
    baseType: "35mm",
    image: "images/home/CP11_Valkyrie.jpg",
    expansion: "CP11",
  },
  {
    _id: "22",
    name: "Hela, Queen of Hel",
    alias: "Hela",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 4,
    },

    affiliation: ["Asgardian"],
    attacks: {},
    superpowers: {
      power1: "Hel Forged Blade",
      power2: "Claim Soul",
      power3: "Rain of Hel",
      power4: "Army of Hel",
      power5: "Asgardian",
      power6: "Goddess of Death",
    },
    baseType: "50mm",
    image: "images/home/CP12_Hela.jpg",
    expansion: "CP12",
  },
  {
    _id: "23",
    name: "Loki, God of Mischief",
    alias: "Loki Laufeyson",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Asgardian", "Cabal"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Frost Blast",
      power3: "Illusions",
      power4: "I am a GOD!",
      power5: "Trickster",
      power6: "Asgardian",
      power7: "God of Mischief",
      power8: "Gem Bearer [Mind, Space]",
    },
    baseType: "35mm",
    image: "images/home/CP12_Loki.jpg",
    expansion: "CP12",
  },
  {
    _id: "24",
    name: "Vision",
    alias: "Victor Shade",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 4,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Solar Energy Beam",
      power2: "Synthezoid Avenger",
      power3: "Calculated Trajectory",
      power4: "Synthesis",
      power5: "Rapid Phase",
      power6: "Phasing",
      power7: "Flight",
      power8: "Immunity [Bleed, Poison]",
    },
    baseType: "35mm",
    image: "images/home/CP13_Vision.jpg",
    expansion: "CP13",
  },
  {
    _id: "25",
    name: "Winter Soldier",
    alias: 'James "Bucky" Barnes',
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ["Unaffiliated"],
    attacks: {},
    superpowers: {
      power1: "Assault Rifle",
      power2: "Red Fury",
      power3: "Hydra Tactics",
      power4: "Got Your Back",
      power5: "Spetsnaz Training",
    },
    baseType: "35mm",
    image: "images/home/CP13_WinterSoldier.jpg",
    expansion: "CP13",
  },
  {
    _id: "26",
    name: "Corvus Glaive",
    alias: "Corvus Glaive",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Black Order"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Atom Splitter",
      power3: "Death Blow",
      power4: "Glaive's Edge",
      power5: "Husband of Proxima Midnight",
      power6: "Glaive of Immortality",
      power7: "Gem Bearer [Reality, Time]",
    },
    baseType: "50mm",
    image: "images/home/CP15_CorvusGlaive.jpg",
    expansion: "CP15",
  },
  {
    _id: "27",
    name: "Proxima Midnight",
    alias: "Proxima Midnight",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Black Order"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Spear Throw",
      power3: "Quantum Starburst",
      power4: "Martial Prowess",
      power5: "Wife of Corvus Glaive",
      power6: "Invulnerability",
    },
    baseType: "35mm",
    image: "images/home/CP15_ProximaMidnight.jpg",
    expansion: "CP15",
  },
  {
    _id: "28",
    name: "Gamora",
    alias: "Gamora",
    statistics: {
      health: 6,
      speed: "L",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["A-Force", "Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "God Slayer",
      power2: "Cosmic Assassin",
      power3: "Assassin Leap",
      power4: "Martial Prowess",
      power5: "Deadliest Woman in the Galaxy",
      power6: "Stealth",
    },
    baseType: "35mm",
    image: "images/home/CP16_Gamora.jpg",
    expansion: "CP16",
  },
  {
    _id: "29",
    name: "Nebula",
    alias: "Nebula",
    statistics: {
      health: 4,
      speed: "M",
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ["Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Blaster Pistol",
      power3: "Show Sword Assault",
      power4: "Assassin",
      power5: "Cybernetic Enhancements",
      power6: "Immunity [Bleed, Poison, Stun]",
    },
    baseType: "35mm",
    image: "images/home/CP16_Nebula.jpg",
    expansion: "CP16",
  },
  {
    _id: "30",
    name: "Rocket Raccoon",
    alias: "Rocket Raccoon",
    statistics: {
      health: 3,
      speed: "M",
      height: 1,
      points: 2,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "Plasma Rifle",
      power2: "Hadron Enforcer",
      power3: "Booby Traps",
      power4: "Personal Bodyguards",
      power5: "Nimble",
      power6: "Small Stature",
    },
    baseType: "35mm",
    image: "images/home/CP17_Rocket.jpg",
    expansion: "CP17",
  },
  {
    _id: "31",
    name: "Groot",
    alias: "I Am Groot",
    statistics: {
      health: 7,
      speed: "S",
      height: 3,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "I Am Groot!",
      power3: "Living Plant",
      power4: "Tangling Vines",
    },
    baseType: "50mm",
    image: "images/home/CP17_Groot.jpg",
    expansion: "CP17",
  },
  {
    _id: "32",
    name: "Star-lord",
    alias: "Peter Quill",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "Elemental Gun",
      power2: "Full Auto",
      power3: "Winging It",
      power4: "Hit And Run",
      power5: "Plucky Attitude",
      power6: "Flight",
      power7: "Gem Bearer [Power]",
    },
    baseType: "35mm",
    image: "images/home/CP18_Starlord.jpg",
    expansion: "CP18",
  },
  {
    _id: "33",
    name: "Black Dwarf",
    alias: "Black Dwarf",
    statistics: {
      health: 6,
      speed: "S",
      height: 4,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Black Order"],
    attacks: {},
    superpowers: {
      power1: "Axe Strike",
      power2: "Brutal End",
      power3: "Black Fury",
      power4: "Enforced Oblivion",
      power5: "Intimidating Presence",
      power6: "Invulnerable Skin",
    },
    baseType: "65mm",
    image: "images/home/CP19_BlackDwarf.png",
    expansion: "CP19",
  },
  {
    _id: "34",
    name: "Ebony Maw",
    alias: "Ebony Maw",
    statistics: {
      health: 7,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 2,
      energy: 4,
      mystic: 6,
    },

    affiliation: ["Black Order"],
    attacks: {},
    superpowers: {
      power1: "Black Tongue",
      power2: "Herald of Doom",
      power3: "Telekinetic Powerhouse",
      power4: "Telekinetic Deflection",
      power5: "Mind over Matter",
      power6: "Incredible Psychic Potential",
      power7: "Flight",
      power8: "Gem Bearer [Mind, Space]",
    },
    baseType: "35mm",
    image: "images/home/CP19_EbonyMaw.png",
    expansion: "CP19",
  },
  {
    _id: "35",
    name: "Drax the Destroyer",
    alias: "Drax",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ["Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "Blades",
      power2: "Headbutt",
      power3: "Titan Killer",
      power4: "The Destroyer",
      power5: "Driven By Vengeance",
      power6: "I Can Take It",
    },
    baseType: "35mm",
    image: "images/home/CP20_Drax.png",
    expansion: "CP20",
  },
  {
    _id: "36",
    name: "Ronan the Accuser",
    alias: "Ronan the Accuser",
    statistics: {
      health: 6,
      speed: "M",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ["Inhumans", "Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Universal Weapon",
      power3: "Kree Justice",
      power4: "Judgment",
      power5: "The Accuser",
      power6: "Gem Bearer [Power]",
      power7: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP20_Ronan.png",
    expansion: "CP20",
  },
  {
    _id: "37",
    name: "Green Goblin",
    alias: "Norman Osborn",
    statistics: {
      health: 7,
      speed: "M",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Criminal Syndicate", "Spider-Foes"],
    attacks: {},
    superpowers: {
      power1: "Pumpkin Bombs",
      power2: "Night of the Goblin",
      power3: "Osborn Weaponry",
      power4: "Hit and Run",
      power5: "Trick or Treat",
      power6: "Arch Nemesis (Peter Parker)",
      power7: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP21_GreenGoblin.png",
    expansion: "CP21",
  },
  {
    _id: "38",
    name: "Doctor Strange",
    alias: "Stephen Vincent Strange",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ["Convocation", "Defenders", "Midnight Sons"],
    attacks: {},
    superpowers: {
      power1: "Bolts of Bedevilment",
      power2: "Crimson Bands of Cyttorak",
      power3: "Mystic Empowerment",
      power4: "Oshtur's Refuge",
      power5: "Hoggoth's Hoary Wisdom",
      power6: "Eye of Agamotto",
      power7: "Shield of the Seraphim",
      power8: "Flight",
      power9: "Gem Bearer [Soul, Time]",
    },
    baseType: "50mm",
    image: "images/home/CP23_DoctorStrange.png",
    expansion: "CP23",
  },
  {
    _id: "39",
    name: "Wong",
    alias: "Wong",
    statistics: {
      health: 4,
      speed: "M",
      height: 2,
      points: 2,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Convocation", "Defenders", "Midnight Sons"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Faithful Assistant",
      power3: "Meditate",
      power4: "The Vishanti's Blessing",
      power5: "Servant to the Sorcerer Supreme",
    },
    baseType: "35mm",
    image: "images/home/CP23_Wong.png",
    expansion: "CP23",
  },
  {
    _id: "40",
    name: "Black Widow, Agent of S.H.I.E.L.D.",
    alias: "Natasha Romanoff",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["A-Force", "Avengers"],
    attacks: {},
    superpowers: {
      power1: "Automatic Pistol",
      power2: "Tear Gas",
      power3: "Widow's Kiss",
      power4: "Interrogate",
      power5: "Parting Shot",
      power6: "Stealth",
    },
    baseType: "35mm",
    image: "images/home/CP24_BlackWidow.png",
    expansion: "CP24",
  },
  {
    _id: "41",
    name: "Hawkeye",
    alias: "Clinton Barton",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers", "Defenders"],
    attacks: {},
    superpowers: {
      power1: "Arrow Shot",
      power2: "Hook Arrow",
      power3: "Trick Shot",
      power4: "Fast Draw",
    },
    baseType: "35mm",
    image: "images/home/CP24_Hawkeye.png",
    expansion: "CP24",
  },
  {
    _id: "42",
    name: "Thanos, The Mad Titan",
    alias: "Thanos",
    statistics: {
      health: 8,
      speed: "M",
      height: 3,
      points: 6,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Black Order"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Cosmic Blast",
      power3: "Death's Agenda",
      power4: "Cosmic Portal",
      power5: "Death's Decree",
      power6: "Being of Immeasurable Power",
      power7: "Gem Bearer [Mind, Power, Reality, Soul, Space, Time]",
      power8: "Immunity [Stun]",
    },
    baseType: "50mm",
    image: "images/home/CP25_Thanos.png",
    expansion: "CP25",
  },
  {
    _id: "43",
    name: "Wasp (Normal)",
    alias: "Janet Van Dyne",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["A-Force", "Avengers"],
    attacks: {},
    superpowers: {
      power1: "Size-Changing Smack Down",
      power2: "Change Size",
      power3: "Pym Discs",
      power4: "Pym Particle Control",
      power5: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP26_Wasp.png",
    expansion: "CP26",
  },
  {
    _id: "44",
    name: "Wasp (Tiny)",
    alias: "Janet Van Dyne",
    statistics: {
      health: 5,
      speed: "L",
      height: 1,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["A-Force", "Avengers"],
    attacks: {},
    superpowers: {
      power1: "Stinger Blast",
      power2: "Wasp's Fury",
      power3: "Change Size",
      power4: "Tiny Superhero",
      power5: "Stealth",
      power6: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP26_Wasp.png",
    expansion: "CP26",
  },
  {
    _id: "45",
    name: "Ant-Man (Normal)",
    alias: "Scott Lang",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Pym Particle Punch",
      power2: "Bullet Ant Barrage",
      power3: "Change Size",
      power4: "Pym Particle Control",
    },
    baseType: "35mm",
    image: "images/home/CP26_AntMan.png",
    expansion: "CP26",
  },
  {
    _id: "46",
    name: "Ant-Man (Tiny)",
    alias: "Scott Lang",
    statistics: {
      health: 5,
      speed: "S",
      height: 1,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Ant-Sized Uppercut",
      power2: "Change Size",
      power3: "Hitch A Ride",
      power4: "Stealth",
      power5: "Tiny Superhero",
    },
    baseType: "35mm",
    image: "images/home/CP26_AntMan.png",
    expansion: "CP26",
  },
  {
    _id: "47",
    name: "Ghost Rider",
    alias: "Johnathon Blaze",
    statistics: {
      health: 8,
      speed: "M",
      height: 3,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ["Defenders", "Midnight Sons"],
    attacks: {},
    superpowers: {
      power1: "Chains of Damnation",
      power2: "Flames of Hell",
      power3: "Penance Stare",
      power4: "Hell on Wheels",
      power5: "Wicked's Judgement",
      power6: "Spirit of Vengeance",
      power7: "Immunity [Bleed, Hex, Incinerate, Poison]",
    },
    baseType: "65mm",
    image: "images/home/CP27_GhostRider.png",
    expansion: "CP27",
  },
  {
    _id: "48",
    name: "Enchantress",
    alias: "Amora",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 5,
    },

    affiliation: ["Asgard", "Cabal"],
    attacks: {},
    superpowers: {
      power1: "Spurned Affection",
      power2: "Enthrall",
      power3: "Amora's Kiss",
      power4: "Hel Hath No Fury...",
      power5: "Siren's Call",
      power6: "Asgardian",
      power7: "Enchanting",
      power8: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP28_Enchantress.png",
    expansion: "CP28",
  },
  {
    _id: "49",
    name: "Angela",
    alias: "Aldrif Odinsdottir",
    statistics: {
      health: 6,
      speed: "L",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 4,
    },

    affiliation: ["A-Force", "Asgard", "Guardians of the Galaxy"],
    attacks: {},
    superpowers: {
      power1: "Xiphos, the Sword of the Stars",
      power2: "Blades of Ichor",
      power3: "Heven's Wrath",
      power4: "Odindottir's Might",
      power5: "Angelic Assassin",
      power6: "Asgardian",
      power7: "Living Ribbons",
      power8: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP28_Angela.png",
    expansion: "CP28",
  },
  {
    _id: "50",
    name: "Kingpin",
    alias: "Wilson Fisk",
    statistics: {
      health: 7,
      speed: "S",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Cabal", "Criminal Syndicate", "Spider-Foes"],
    attacks: {},
    superpowers: {
      power1: "Headbutt",
      power2: "Cane Laser",
      power3: "Hail to the Kin",
      power4: "Illicit Network",
      power5: "Street-Level Negotiations",
      power6: "Intense Physical Conditioning",
      power7: "Solid Frame",
      power8: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP29_Kingpin.png",
    expansion: "CP29",
  },
  {
    _id: "51",
    name: "Daredevil",
    alias: "Matt Murdock",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Defenders", "Web Warriors"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Baton Hook",
      power3: "Devil's Deliverance",
      power4: "Man Without Fear",
      power5: "Radar Sense",
      power6: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP30_DareDevil.png",
    expansion: "CP30",
  },
  {
    _id: "52",
    name: "Bullseye",
    alias: "Benjamin Poindexter",
    statistics: {
      health: 4,
      speed: "M",
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: ["Cabal", "Crime Syndicate"],
    attacks: {},
    superpowers: {
      power1: "Throwing Knife",
      power2: "Pin Cushion",
      power3: "Hit and Run",
      power4: "I Never Miss",
      power5: "Parting Shot",
    },
    baseType: "35mm",
    image: "images/home/CP30_Bullseye.png",
    expansion: "CP30",
  },
  {
    _id: "53",
    name: "Taskmaster",
    alias: "Anthony Masters",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Criminal Syndicate"],
    attacks: {},
    superpowers: {
      power1: "Sword Strike",
      power2: "Shield Throw",
      power3: "Mnemonic Technique",
      power4: "Photographic Reflexes",
      power5: "Intuitive Pattern Recognition",
      power6: "Martial Artist",
      power7: "Rogue Agent",
    },
    baseType: "35mm",
    image: "images/home/CP32_Taskmaser.png",
    expansion: "CP32",
  },
  {
    _id: "54",
    name: "Punisher",
    alias: "Frank Castle",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Unaffiliated"],
    attacks: {},
    superpowers: {
      power1: "Hip Fire",
      power2: "Aimed Shot",
      power3: "No More Second Chances",
      power4: "Spec Ops Training",
      power5: "War Zone",
      power6: "The Fallen",
    },
    baseType: "35mm",
    image: "images/home/CP32_Punisher.png",
    expansion: "CP32",
  },
  {
    _id: "55",
    name: "Dormammu",
    alias: "Dormammu",
    statistics: {
      health: 10,
      speed: "M",
      height: 5,
      points: 8,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 5,
    },

    affiliation: ["Dark Dimension"],
    attacks: {},
    superpowers: {
      power1: "Shadow Bolt",
      power2: "Incantation of Obliteration",
      power3: "Flames of the Faltine",
      power4: "Not of this Dimension",
      power5: "Feel the Power of Darkness",
      power6: "Master of the Realm of Darkness",
      power7: "Flight",
      power8: "Immunity [Bleed, Incinerate, Stagger]",
    },
    baseType: "65mm",
    image: "images/home/CP33_Dormammu.png",
    expansion: "CP33",
  },
  {
    _id: "56",
    name: "Black Bolt",
    alias: "Blackagar Boltagon",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 2,
    },

    affiliation: ["Inhumans"],
    attacks: {},
    superpowers: {
      power1: "Energy Bolt",
      power2: "Master Punch",
      power3: "King of the Inhumans",
      power4: "Focus Power",
      power5: "Anti-Graviton Field",
      power6: "Inhuman",
      power7: "Flight",
      power8: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP34_BlackBolt.png",
    expansion: "CP34",
  },
  {
    _id: "57",
    name: "Medusa",
    alias: "Medusalith Amazquelin-Boltagon",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["A-Force", "Inhumans"],
    attacks: {},
    superpowers: {
      power1: "Braid Bash",
      power2: "Split Ends",
      power3: "Hair Flip",
      power4: "Royal Decree",
      power5: "Inhuman",
      power6: "Living Strands",
      power7: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP34_Medusa.png",
    expansion: "CP34",
  },
  {
    _id: "58",
    name: "Crystal",
    alias: "Crystal Amaquelin",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["A-Force", "Inhumans"],
    attacks: {},
    superpowers: {
      power1: "Earth-Shaker",
      power2: "Hurricane Blast",
      power3: "Hydrokinesis",
      power4: "Volcanic Surge",
      power5: "Elemental Onslaught",
      power6: "Elemental Empowerment",
      power7: "Inhuman",
      power8: "Flight",
      power9: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP35_Crystal.png",
    expansion: "CP35",
  },
  {
    _id: "59",
    name: "Lockjaw",
    alias: "LockJaw",
    statistics: {
      health: 6,
      speed: "S",
      height: 3,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Inhumans"],
    attacks: {},
    superpowers: {
      power1: "Bite",
      power2: "DROP IT!",
      power3: "Inter-Dimensional Bloodhound",
      power4: "Teleport",
      power5: "Inhuman",
      power6: "Who's a Good Boy?",
      power7: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP35_Lockjaw.png",
    expansion: "CP35",
  },
  {
    _id: "62",
    name: "Amazing Spider-Man",
    alias: "Peter Parker",
    statistics: {
      health: 6,
      speed: "L",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["Defenders", "Web Warriors"],
    attacks: {},
    superpowers: {
      power1: "Spider Strike",
      power2: "Whatever a Spider Can",
      power3: "Friendly Neighborhood Spider-Team",
      power4: "Web Swing",
      power5: "Witty Banter",
      power6: "Masterd Spider-Sense",
      power7: "Wall Crawler",
    },
    baseType: "50mm",
    image: "images/home/CP37_TheAmazingSpiderman.png",
    expansion: "CP37",
  },
  {
    _id: "61",
    name: "Black Cat",
    alias: "Felecia Hardy",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: [
      "A-Force",
      "Criminal Syndicate",
      "Midnight Sons",
      "Web Warriors",
    ],
    attacks: {},
    superpowers: {
      power1: "Cat Claws",
      power2: "Troublemaker",
      power3: "Grappling Hook",
      power4: "Master Cat Burglar",
      power5: "Bad Luck",
      power6: "Stealth",
    },
    baseType: "50mm",
    image: "images/home/CP37_BlackCat.png",
    expansion: "CP37",
  },
  {
    _id: "62",
    name: "Captain America",
    alias: "Sam Wilson",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Shield Throw",
      power2: "Redwing Assault",
      power3: "All New, All Different (Affiliation: Avengers)",
      power4: "Charge",
      power5: "Air Lift",
      power6: "Vibranium Shield",
      power7: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP38_CaptainAmerica.png",
    expansion: "CP38",
  },
  {
    _id: "63",
    name: "War Machine",
    alias: "James Rhodes",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Metal Storm",
      power2: "Rocket Pods",
      power3: "Empty the Clip",
      power4: "Titanium Armor Plating",
      power5: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP38_WarMachine.png",
    expansion: "CP38",
  },
  {
    _id: "64",
    name: "She-Hulk",
    alias: "Jennifer Walters",
    statistics: {
      health: 20,
      speed: "M",
      height: 3,
      points: 6,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["A-Force", "Avengers"],
    attacks: {},
    superpowers: {
      power1: "Sensational Uppercut",
      power2: "The Defense Rests",
      power3: "Defenders of Arcadia (Affiliation: A-Force)",
      power4: "Clear the Court",
      power5: "Superior Weight Training",
      power6: "Legal Defense",
      power7: "Gamma Transfusion",
      power8: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP39_SheHulk.png",
    expansion: "CP39",
  },
  {
    _id: "65",
    name: "Wolverine",
    alias: "James Logan Howlett",
    statistics: {
      health: 7,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 2,
    },

    affiliation: ["Avengers", "Defenders", "Uncanny X-Men", "X-force"],
    attacks: {},
    superpowers: {
      power1: "Adamantium Slash",
      power2: "Berserker Barrage",
      power3: "The Best At What I Do...",
      power4: "Adamantium Skeleton",
      power5: "Healing Factor [2]",
      power6: "Immunity [Stun]",
    },
    baseType: "35mm",
    image: "images/home/CP40_Wolverine.png",
    expansion: "CP40",
  },
  {
    _id: "66",
    name: "Sabretooth",
    alias: "Victor Creed",
    statistics: {
      health: 6,
      speed: "L",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Brotherhood of Evil Mutants", "Cabal", "X-Force"],
    attacks: {},
    superpowers: {
      power1: "Claw Slash",
      power2: "Savage Predator",
      power3: "No Mercy",
      power4: "Untamed Force",
      power5: "Aggressive",
      power6: "Healing Factor [1]",
    },
    baseType: "35mm",
    image: "images/home/CP40_Sabretooth.png",
    expansion: "CP40",
  },
  {
    _id: "67",
    name: "Cyclops",
    alias: "Scott Summers",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Uncanny X-Men"],
    attacks: {},
    superpowers: {
      power1: "Optic Blast",
      power2: "Optic Devastation",
      power3: "X-Men Blue (Affiliation: Uncanny X-Men)",
      power4: "Field Leader",
      power5: "Hit and Run",
      power6: "Quick Draw",
    },
    baseType: "35mm",
    image: "images/home/CP41_Cyclops.png",
    expansion: "CP41",
  },
  {
    _id: "68",
    name: "Storm",
    alias: "Ororo Munroe",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["A-Force", "Uncanny X-Men", "Wakanda"],
    attacks: {},
    superpowers: {
      power1: "Lightning Bolt",
      power2: "Ice Blizzard",
      power3: "Hurricane",
      power4: "X-Men Gold (Affiliation: Uncanny X-Men)",
      power5: "Eye of the Storm",
      power6: "Tempest",
      power7: "Goddess of Storms",
      power8: "Flight",
      power9: "Immunity [Shock]",
    },
    baseType: "35mm",
    image: "images/home/CP41_Storm.png",
    expansion: "CP41",
  },
  {
    _id: "69",
    name: "Magneto",
    alias: "Max Eisenhardt",
    statistics: {
      health: 6,
      speed: "S",
      height: 2,
      points: 6,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 6,
    },

    affiliation: ["Brotherhood of Mutants", "Cabal"],
    attacks: {},
    superpowers: {
      power1: "From the Ruins... (Affiliation: Brotherhood of Mutants)",
      power2: "Fatal Attraction",
      power3: "Force Projection",
      power4: "Master of Magnetism",
      power5: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP42_Magneto.png",
    expansion: "CP42",
  },
  {
    _id: "70",
    name: "Toad",
    alias: "Mortimore Toynbee",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Brotherhood of Mutants"],
    attacks: {},
    superpowers: {
      power1: "Tongue Lash",
      power2: "Spit Acid",
      power3: "Finders Keepers",
      power4: "Hop",
      power5: "Slippery",
      power6: "Prehensile Tongue",
      power7: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP42_Toad.png",
    expansion: "CP42",
  },
  {
    _id: "71",
    name: "Beast",
    alias: "Hank McCoy",
    statistics: {
      health: 6,
      speed: "M",
      height: 3,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Avengers", "Inhumans", "Uncannny X-Men"],
    attacks: {},
    superpowers: {
      power1: "Acrobatic Strike",
      power2: "Animalistic Freestyle",
      power3: "Baser Instincts",
      power4: "Stars and Garters",
      power5: "Disconcerting, Yet Provatative!",
      power6: "Wall Crawler",
    },
    baseType: "50mm",
    image: "images/home/CP43_Beast.png",
    expansion: "CP43",
  },
  {
    _id: "72",
    name: "Mystique",
    alias: "Raven Darkhölme",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Brotherhood of Mutants", "Cabal"],
    attacks: {},
    superpowers: {
      power1: "Pistol",
      power2: "Espionage",
      power3: "Freedon Force (Affiliation: Brotherhood of Mutants)",
      power4: "Expert Sabotage",
      power5: "Martial Artist",
      power7: "Shapeshifter",
      power6: "Stealth",
    },
    baseType: "35mm",
    image: "images/home/CP43_Mystique.png",
    expansion: "CP43",
  },
  {
    _id: "73",
    name: "Deadpool",
    alias: "Wade Wilson",
    statistics: {
      health: 4,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Avengers", "X-Force"],
    attacks: {},
    superpowers: {
      power1: "Stab",
      power2: "Bang",
      power3: "Deodenum Poke",
      power4: "Merc With a Mouth",
      power5: "I Know Karate",
      power6: "Unicorns, Rainbows, and Sugar Plums Dancing Through My Head",
      power7: "Healing Factor [2]",
    },
    baseType: "35mm",
    image: "images/home/CP45_Deadpool.png",
    expansion: "CP45",
  },
  {
    _id: "74",
    name: "Bob, Agent of Hydra",
    alias: "Robert Dobalina",
    statistics: {
      health: 3,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 2,
    },

    affiliation: ["Cabal"],
    attacks: {},
    superpowers: {
      power1: "Hydra Pistol",
      power2: "Excessive Violence",
      power3: "Hydra Tactics",
      power4: "Make It Spicy, Bob!",
      power5: "Muy Caliente",
    },
    baseType: "35mm",
    image: "images/home/CP45_BobAgentofHydra.png",
    expansion: "CP45",
  },
  {
    _id: "75",
    name: "Mister Sinister",
    alias: "Nathaniel Essex",
    statistics: {
      health: 6,
      speed: "M",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Cabal"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "Genetic Splicing",
      power3: "Recombinant Disintegration",
      power4: "Engeered Perfection",
      power5: "Genetic Negotiation",
      power6: "Such Fun Little Playthings",
      power7: "Molecular Regeneration",
      power8: "DNA Database",
      power9: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP46_MisterSinister.png",
    expansion: "CP46",
  },
  {
    _id: "76",
    name: "Cable",
    alias: "Nathan Summers",
    statistics: {
      health: 6,
      speed: "S",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Avengers", "Uncanny X-Men", "X-Force"],
    attacks: {},
    superpowers: {
      power1: "Plasma Rifle",
      power2: "Askani'son",
      power3: "Wetworks (Affiliation: X-Force)",
      power4: "Body Slide by One",
      power5: "Omega Level Threat",
      power6: "Telekinetic Shield",
      power7: "Techno-Organic Virus Suppression",
      power8: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP47_Cable.png",
    expansion: "CP47",
  },
  {
    _id: "77",
    name: "Domino",
    alias: "Neena Thurman",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["A-Force", "Uncanny X-Men", "X-Force"],
    attacks: {},
    superpowers: {
      power1: "Automatic Pistols",
      power2: "Grenade Bounce",
      power3: "Lucky Shot",
      power4: "Probability Manipulation",
      power5: "Things Tend To Go My Way",
    },
    baseType: "35mm",
    image: "images/home/CP47_Domino.png",
    expansion: "CP47",
  },
  {
    _id: "78",
    name: "Blade",
    alias: "Eric Brooks",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Avengers", "Defenders", "Midnight Sons"],
    attacks: {},
    superpowers: {
      power1: "Katana",
      power2: "Throwing Glaive",
      power3: "Night of the Dhampir",
      power4: "Bump in the Night (Affiliation: Midnight Sons)",
      power5: "Half-Blood Physiology",
      power6: "Supernatural Sense",
      power7: "Vampiric Immortality",
    },
    baseType: "35mm",
    image: "images/home/CP48_Blade.png",
    expansion: "CP48",
  },
  {
    _id: "79",
    name: "Moon Knight",
    alias: "Marc Spector",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Defenders", "Midnight Sons", "Web Warriors"],
    attacks: {},
    superpowers: {
      power1: "Bo Staff",
      power2: "Throwing Crescents",
      power3: "Avatar of Khonshu",
      power4: "Chosen of Khonshu",
      power5: "Multiple Personalities ",
      power6: "Stealth",
      power7: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP48_Moonknight.png",
    expansion: "CP48",
  },
  {
    _id: "80",
    name: "Luke Cage",
    alias: "Carl Lucas",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers", "Defenders"],
    attacks: {},
    superpowers: {
      power1: "Power Man Punch",
      power2: "Sweet Christmas",
      power3: "Street Fighter",
      power4: "Too Dangerous to Ignore",
      power5: "Unbreakable Skin",
      power6: "Immunity [Bleed]",
    },
    baseType: "35mm",
    image: "images/home/CP49_LukeCage.png",
    expansion: "CP49",
  },
  {
    _id: "81",
    name: "Iron Fist",
    alias: "Danny Rand",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers", "Defenders", "Midnight Sons"],
    attacks: {},
    superpowers: {
      power1: "Chi Strike",
      power2: "Flying Kick",
      power3: "The Iron Fist",
      power4: "Street Fighter",
      power5: "Immortal Weapon",
      power6: "Master Martial Artist",
    },
    baseType: "35mm",
    image: "images/home/CP49_IronFist.png",
    expansion: "CP49",
  },
  {
    _id: "82",
    name: "Mysterio",
    alias: "Quentin Beck",
    statistics: {
      health: 6,
      speed: "S",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 1,
      energy: 1,
      mystic: 5,
    },

    affiliation: ["Cabal", "Criminal Syndicate", "Spider-Foes"],
    attacks: {},
    superpowers: {
      power1: "Hypnosis Gas",
      power2: "Curtain Call",
      power3: "Tricks and Traps",
      power4: "Master of Illusions",
      power5: "Smoke and Mirrors",
      power6: "Stealth",
      power7: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP50_Mysterio.png",
    expansion: "CP50",
  },
  {
    _id: "83",
    name: "Carnage",
    alias: "Cletus Kasady",
    statistics: {
      health: 7,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 5,
      energy: 1,
      mystic: 1,
    },

    affiliation: ["Spider-Foes"],
    attacks: {},
    superpowers: {
      power1: "Symbiote Tendrils",
      power2: "Maximum Carnage",
      power3: "Sadistic Glee",
      power4: "Paint the Town Red",
      power5: "Arch Nemesis [Eddie Brock]",
      power6: "Symbiotic Serial Killer",
      power7: "Wall Crawler",
    },
    baseType: "50mm",
    image: "images/home/CP50_Carnage.png",
    expansion: "CP50",
  },
  {
    _id: "84",
    name: "Hulkbuster",
    alias: "Tony Stark",
    statistics: {
      health: 13,
      speed: "M",
      height: 4,
      points: 6,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Heavy Repulsor Blast",
      power2: "Meteor Punch",
      power3: "Hulkbusters (Affiliation: Avengers)",
      power4: "Hit and Run",
      power5: "Now I'm Mad",
      power6: "Built to Take It",
      power7: "Enhanced Support Systems [Iron Man (Hulkbuster)]",
    },
    baseType: "50mm",
    image: "images/home/CP52_Hulkbuster.png",
    expansion: "CP52",
  },
  {
    _id: "85",
    name: "Iron Man (Hulkbuster)",
    alias: "Tony Stark",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 6,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Avengers"],
    attacks: {},
    superpowers: {
      power1: "Rapid Repulsor Blast",
      power2: "Hulkbusters (Affiliation: Avengers)",
      power3: "Always Have a Backup",
      power4: "New Plan",
      power5: "Secondary Support Suit",
      power6: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP52_Hulkbuster.png",
    expansion: "CP52",
  },
  {
    _id: "86",
    name: "Jean Grey",
    alias: "Jean Grey",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 5,
    },

    affiliation: ["Uncanny X-Men"],
    attacks: {},
    superpowers: {
      power1: "Psionic Bolt",
      power2: "Telekinetic Force",
      power3: "Battlefield Manipulation",
      power4: "Matter Transmutaion",
      power5: "Shield Mind",
      power6: "Latent Psychic Potential",
      power7: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP53_JeanGrey.png",
    expansion: "CP53",
  },
  {
    _id: "87",
    name: "Cassandra Nova",
    alias: "Cassandra Nova Xavier",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Cabal"],
    attacks: {},
    superpowers: {
      power1: "Psionic Bolt",
      power2: "Mind Possession",
      power3: "Flesh Manipulation",
      power4: "Biokinesis",
      power5: "Psychic Distraction",
      power6: "Telekinetic Defelction",
      power7: "Telepathic Cloak",
      power8: "Flight",
      power9: "Healing Factor [1]",
    },
    baseType: "35mm",
    image: "images/home/CP53_CassandraNova.png",
    expansion: "CP53",
  },
  {
    _id: "88",
    name: "Omega Red",
    alias: "Arkady Gregorivich Rossovich",
    statistics: {
      health: 6,
      speed: "S",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Cabal", "Criminal Syndicate"],
    attacks: {},
    superpowers: {
      power1: "Carbonadium Coils",
      power2: "Red Terror",
      power3: "Death Factor",
      power4: "Ensnare",
      power5: "Carbonadium Armor",
      power6: "Death Spores",
      power7: "Immunity [Poison]",
    },
    baseType: "50mm",
    image: "images/home/CP54_OmegaRed.png",
    expansion: "CP54",
  },

  {
    _id: "89",
    name: "Nick Fury",
    alias: "Nick Fury Jr.",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 2,
    },

    affiliation: [""],
    attacks: {},
    superpowers: {
      power1: "",
    },
    baseType: "50mm",
    image: "images/home/CP55_NickFury.png",
    expansion: "CP55",
  },
  {
    _id: "90",
    name: "Juggernaut",
    alias: "Cain Marko",
    statistics: {
      health: 8,
      speed: "S",
      height: 4,
      points: 5,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 5,
    },

    affiliation: ["Brotherhood of Mutants"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "I'm the Juggernaut",
      power3: "Nothing Stops the Juggernaut!",
      power4: "Nice Punch...",
      power5: "Helmet",
      power6: "Unstoppable Momentum",
      power7: "Immunity [Stun]",
    },
    baseType: "50mm",
    image: "images/home/CP56_Juggernaut.png",
    expansion: "CP56",
  },
  {
    _id: "91",
    name: "Colossus",
    alias: "Piotr Rasputin",
    statistics: {
      health: 6,
      speed: "S",
      height: 3,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["X-Force"],
    attacks: {},
    superpowers: {
      power1: "Strike",
      power2: "X-Slam",
      power3: "Playing Catch",
      power4: "Big Brother",
      power5: "Bozhe Moi",
      power6: "Organic Steel",
      power7: "Immunity [Bleed]",
    },
    baseType: "TBD",
    image: "images/home/CP57_Colossus.png",
    expansion: "CP57",
  },
  {
    _id: "92",
    name: "Magik",
    alias: "Illyana Rasputin",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Convocation"],
    attacks: {},
    superpowers: {
      power1: "Bolts of Oshtur",
      power2: "Soulsword",
      power3: "Darkchylde",
      power4: "Limbo Step",
      power5: "Sorcerer Supreme of Limbo",
    },
    baseType: "TBD",
    image: "images/home/CP57_Magik.png",
    expansion: "CP57",
  },
  {
    _id: "93",
    name: "Lizard",
    alias: "Curtis Connor",
    statistics: {
      health: 6,
      speed: "M",
      height: 3,
      points: 3,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Spider-Foes"],
    attacks: {},
    superpowers: {
      power1: "Tail Whip",
      power2: "Cold-Blooded",
      power3: "Biochemical Breakthrough",
      power4: "Thick Hide",
      power5: "Healing Factor [1]",
      power6: "Wall Crawler",
    },
    baseType: "50mm",
    image: "images/home/CP58_Lizard.png",
    expansion: "CP58",
  },
  {
    _id: "94",
    name: "Kraven",
    alias: "Sergei Nikolaevich Kravinoff",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Criminal Syndicate", "Spider-Foes"],
    attacks: {},
    superpowers: {
      power1: "Kurri Strike",
      power2: "Spear Thrust",
      power3: "Corner the Beast",
      power4: "Expert Tracker",
      power5: "Elixer of Calypso",
    },
    baseType: "50mm",
    image: "images/home/CP58_Kraven.png",
    expansion: "CP58",
  },
  {
    _id: "97",
    name: "Gambit",
    alias: "Remy LeBeau",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["TBD"],
    attacks: {},
    superpowers: {
      power1: "Bo Staff",
      power2: "Kinetic Ace",
      power3: "52 Card Pickup",
      power4: "Accelerate Charge",
      power5: "A Little Something Extra",
      power6: "Enhanced Agility",
    },
    baseType: "TBD",
    image: "images/home/CP60_Gambit.png",
    expansion: "CP60",
  },
  {
    _id: "98",
    name: "Rogue",
    alias: "Anna Marie LeBeau",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 4,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["TBD"],
    attacks: {},
    superpowers: {
      power1: "Absorbing Strike",
      power2: "Southern Hospitality",
      power3: "Charge",
      power4: "Marvelous Strength",
      power5: "Mutant Absorption",
      power6: "Kree-Mutant Physiology",
      power7: "Flight",
      power8: "Immunity [Poison]",
    },
    baseType: "TBD",
    image: "images/home/CP60_Rogue.png",
    expansion: "CP60",
  },
  {
    _id: "99",
    name: "Sin",
    alias: "Sinthea Schmidt",
    statistics: {
      health: 4,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Criminal Syndicate", "Cabal"],
    attacks: {},
    superpowers: {
      power1: "Automatic Pistol",
      power2: "Make It Personal",
      power3: "Red Mayhem (Affiliation: Cabal)",
      power4: "Hit and Run",
      power5: "Partners in Crime",
      power6: "Heir to the Wicked",
      power7: "Stealth",
    },
    baseType: "35mm",
    image: "images/home/CP61_Sin.png",
    expansion: "CP61",
  },
  {
    _id: "100",
    name: "Viper",
    alias: "Ophelia Sarkissian",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Cabal"],
    attacks: {},
    superpowers: {
      power1: "Poisoned Blade",
      power2: "Assassin's Pistol",
      power3: "Viper Strike",
      power4: "Displacement Ring",
      power5: "Coiled Serpent",
      power6: "Stealth",
    },
    baseType: "35mm",
    image: "images/home/CP61_Viper.png",
    expansion: "CP61",
  },
  {
    _id: "101",
    name: "Ms. Marvel",
    alias: "Kamala Khan",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["Avengers", "Inhumans"],
    attacks: {},
    superpowers: {
      power1: "Morpho-Punch",
      power2: "Embiggen",
      power3: "Take Out The Trash",
      power4: "Inhuman",
      power5: "Immunity [Poison]",
    },
    baseType: "35mm",
    image: "images/home/CP62_MsMarvel.png",
    expansion: "CP62",
  },
  {
    _id: "102",
    name: "Ms. Marvel (Embiggened)",
    alias: "Kamala Khan",
    statistics: {
      health: 5,
      speed: "M",
      height: 4,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 3,
    },

    affiliation: ["Avengers", "Inhumans"],
    attacks: {},
    superpowers: {
      power1: "High Five",
      power2: "Inhuman",
      power3: "Morphogenetics",
      power4: "Polymorph",
      power5: "Immunity [Poison]",
    },
    baseType: "65mm",
    image: "images/home/CP62_MsMarvel.png",
    expansion: "CP62",
  },
  {
    _id: "103",
    name: "Scarlet Witch",
    alias: "Wanda Maximoff",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 4,
      mystic: 4,
    },

    affiliation: ["A-Force", "Avengers", "Defenders", "Brotherhood of Mutants"],
    attacks: {},
    superpowers: {
      power1: "Hex Bolt",
      power2: "Cruel Twist",
      power3: "Telekinesis",
      power4: "Curse",
      power5: "Chosen of Chthon",
      power6: "Hex Field",
      power7: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP63_ScarletWitch.png",
    expansion: "CP63",
  },
  {
    _id: "104",
    name: "Quicksilver",
    alias: "Pietro Maximoff",
    statistics: {
      health: 5,
      speed: "L",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 3,
    },

    affiliation: ["Avengers", "Brotherhood of Mutants", "Inhumans"],
    attacks: {},
    superpowers: {
      power1: "Supersonic Strike",
      power2: "Cyclonic Vortex",
      power3: '"speed"ster',
      power4: "Can't Catch Me",
      power5: "Supersonic Reflexes",
      power6: "Wall Crawler",
    },
    baseType: "35mm",
    image: "images/home/CP63_Quicksilver.png",
    expansion: "CP63",
  },
  {
    _id: "105",
    name: "Ancient One",
    alias: "Ancient One",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 5,
    },

    affiliation: ["Convocation", "Defenders"],
    attacks: {},
    superpowers: {
      power1: "Shards of Seraphim",
      power2: "Fangs of Farallah",
      power3: "Astral Strike",
      power4: "Mists of Hoggoth",
      power5: "Winds of Watoomb",
      power6: "Keeper of the Eye of Agamotto",
      power7: "Martial Artist",
    },
    baseType: "35mm",
    image: "images/home/CP64_AncientOne.png",
    expansion: "CP64",
  },
  {
    _id: "106",
    name: "Baron Mordo",
    alias: "Karl Amadeus Mordo",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 4,
      mystic: 4,
    },

    affiliation: ["Cabal", "Convocation"],
    attacks: {},
    superpowers: {
      power1: "Staf of the Living Tribunal",
      power2: "Bolts of Bishru",
      power3: "Rains fo Raggadorr",
      power4: "Master of the Occult",
      power5: "Soul Barb",
      power6: "Ferocity of Cyttorak",
      power7: "Vaulting Boots of Valtor",
      power8: "Flight",
    },
    baseType: "35mm",
    image: "images/home/CP64_Mordo.png",
    expansion: "CP64",
  },
  {
    _id: "107",
    name: "Doctor Voodoo",
    alias: "Jericho Drumm",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 4,
    },

    affiliation: ["Avengers", "Convocation", "Midnight Sons"],
    attacks: {},
    superpowers: {
      power1: "Sprit Venom",
      power2: "Staff of Legba",
      power3: "Possession",
      power4: "Spiritual Strength",
      power5: "Recall Spirit",
      power6: "Spirit of Brother Daniel",
      power7: "Flight",
      power8: "Immunity [Hex, Incinerate]",
    },
    baseType: "50mm",
    image: "images/home/CP65_DoctorVoodoo.png",
    expansion: "CP65",
  },
  {
    _id: "108",
    name: "Hood (Normal)",
    alias: "Parker Robbins",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Cabal", "Crime Syndicate"],
    attacks: {},
    superpowers: {
      power1: "Hex Shot",
      power2: "Dark Lightning",
      power3: "Black Arts",
      power4: "Invisibility Cloak",
      power5: "Possessed by Nasanti",
    },
    baseType: "35mm",
    image: "images/home/CP65_Hood.png",
    expansion: "CP65",
  },
  {
    _id: "109",
    name: "Hood (Possessed)",
    alias: "Parker Robbins",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 2,
      energy: 2,
      mystic: 3,
    },

    affiliation: ["Cabal", "Crime Syndicate"],
    attacks: {},
    superpowers: {
      power1: "Razor Talons",
      power2: "Empowered Dark Lightning",
      power3: "Charge",
      power4: "Demonic Resilience",
      power5: "Mystic Vulnerability",
    },
    baseType: "35mm",
    image: "images/home/CP65_HoodPossessed.png",
    expansion: "CP65",
  },
  {
    _id: "110",
    name: "Doctor Strange, Sorcerer Supreme",
    alias: "Stephen Vincent Strange",
    statistics: {
      health: 6,
      speed: "M",
      height: 2,
      points: 5,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 5,
    },

    affiliation: ["Convocation", "Defenders", "Midnight Sons"],
    attacks: {},
    superpowers: {
      power1: "Baleful Bolts of Balthakk",
      power2: "Deadly Daggers of Daveroth",
      power3: "Shining Circle of the Serphim",
      power4: 'Scalpel of St"range"',
      power5: "Chosen of the Vishanti",
      power6: "Eye of Agamotto",
      power7: 'Mystic Armor of St"range"',
      power8: "Flight",
    },
    baseType: "50mm",
    image: "images/home/CP67_DoctorStrange.png",
    expansion: "CP67",
  },
  {
    _id: "111",
    name: "Clea",
    alias: "Clea",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 4,
    },
    defence: {
      physical: 2,
      energy: 3,
      mystic: 4,
    },

    affiliation: ["Convocation", "Defenders"],
    attacks: {},
    superpowers: {
      power1: "Demon Claws of Denak",
      power2: "Icy Tendrils of Ikthalon",
      power3: "Descendant of the Faultine",
      power4: "Oshtur's Mighty Hand",
      power5: "Vapors of Dormammu",
      power6: "Immunity [Incinerate]",
    },
    baseType: "50mm",
    image: "images/home/CP67_Clea.png",
    expansion: "CP67",
  },
  //CP68 Sanctum Sanctorum
  //CP69 ?/?
  //CP70 ?/?
  {
    _id: "116",
    name: "Honey Badger",
    alias: "Gabrielle Kinney",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 2,
    },
    defence: {
      physical: 3,
      energy: 2,
      mystic: 2,
    },

    affiliation: [""],
    attacks: {
      attack1: {
        name: "Claw Slash",
        range: 2,
        damage: 5,
        cost: 0,
        type: "Physical",
        attackDesc: [
          "After this attack is resolved, this character gains power equal to the damage dealt",
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Bleed",
            text: "Bleed: After this attack is resolved, the target character gains the Bleed special condition",
          },
        ],
      },
    },
    superpowers: {
      power1: "Too Dangerous to Ignore",
      power2: "Anklebiter",
      power3: "Lil' Sis",
      power4: "Healing Factor [1]",
    },
    baseType: "50mm",
    image: "images/home/CP71_Honeybadger.png",
    expansion: "CP71",
  },
  {
    _id: "116",
    name: "X-23",
    alias: "Laura Kinney",
    statistics: {
      health: 5,
      speed: "M",
      height: 2,
      points: 3,
    },
    defence: {
      physical: 3,
      energy: 3,
      mystic: 2,
    },

    affiliation: [""],
    attacks: {
      attack1: {
        name: "Adamantium Slash",
        range: 2,
        damage: 5,
        cost: 0,
        type: "Physical",
        attackDesc: [
          "After this attack is resolved, this character gains power equal to the damage dealt",
        ],
        special: [
          {
            wildcardcost: "1",
            skullcost: "",
            critcost: "",
            keyword: "Bleed",
            text: "Bleed: After this attack is resolved, the target character gains the Bleed special condition",
          },
        ],
      },
    },
    superpowers: {
      power1: "Too Dangerous to Ignore",
      power2: "Anklebiter",
      power3: "Lil' Sis",
      power4: "Healing Factor [1]",
    },
    baseType: "50mm",
    image: "images/home/CP71_Honeybadger.png",
    expansion: "CP71",
  },
];

export default characters;
